// ═══════════════════════════════════════════════════════════════
// ASTRO CLOCK — ZODIAC DATA (BURÇLAR)
// From Havâss'ın Derinlikleri (Pages 20-31)
// Complete zodiac system with properties, relationships, and incenses
// Arabic Terminology Preservation Rule: Implemented
// ═══════════════════════════════════════════════════════════════

export const ZODIAC_SIGNS = {
  aries: {
    key: "aries",
    name_en: "Aries",
    name_ml_equivalent: "മേഷം",
    name_tr: "Koç",
    name_ar: "الحمل",
    name_en_transliteration: "Al-Hamal",
    name_ml_reading: "അൽ-ഹമൽ",
    symbol: "♈",
    element: "Fire",
    element_ml: "അഗ്നി",
    element_ar: "نار",
    gender: "Masculine",
    gender_ml: "പുരുഷൻ",
    gender_ar: "ذكر",
    ruling_planet: "Mars",
    ruling_planet_ml: "ചൊവ്വ",
    ruling_planet_ar: "المريخ",
    ruling_planet_symbol: "♂",
    metal: "Iron",
    metal_ml: "ഇരുമ്പ്",
    metal_ar: "حديد",
    incense: "Oud & Mastic",
    incense_ml: "ഊദും മാസ്റ്റിക്കും",
    incense_ar: "العود والمصطكي",
    date_range: "March 21 - April 19",
    date_range_ml: "മാർച്ച് 21 - ഏപ്രിൽ 19",
    date_range_start: "March 21",
    date_range_end: "April 19",
    friendly_signs: ["Leo", "Sagittarius", "Gemini", "Aquarius"],
    enemy_signs: ["Cancer", "Capricorn"],
    day_association: "Sunday",
    day_association_tr: "Pazar",
    night_association: "Monday",
    night_association_tr: "Pazartesi",
    letters: ["ا", "ب"],
    letter_names: ["Alif", "Ba"],
    explanation_en: "The warrior, leader, and pioneer. Represents new beginnings, courage, and initiative.",
    explanation_ml: "യോദ്ധാവ്, നേതാവ്, മുൻഗാമി. പുതിയ തുടക്കങ്ങളെയും ധൈര്യത്തെയും ആരംഭത്തെയും പ്രതിനിധീകരിക്കുന്നു."
  },
  taurus: {
    key: "taurus",
    name_en: "Taurus",
    name_ml_equivalent: "ഇടവം",
    name_tr: "Boğa",
    name_ar: "الثور",
    name_en_transliteration: "Al-Thawr",
    name_ml_reading: "അൽ-ഥൗർ",
    symbol: "♉",
    element: "Earth",
    element_ml: "ഭൂമി",
    element_ar: "أرض",
    gender: "Feminine",
    gender_ml: "സ്ത്രീ",
    gender_ar: "أنثى",
    ruling_planet: "Venus",
    ruling_planet_ml: "ശുക്രൻ",
    ruling_planet_ar: "الزهرة",
    ruling_planet_symbol: "♀",
    metal: "Copper",
    metal_ml: "ചെമ്പ്",
    metal_ar: "نحاس",
    incense: "Sandalwood & Musk",
    incense_ml: "ചന്ദനവും പുനുകും",
    incense_ar: "الصندل والمسك",
    date_range: "April 20 - May 20",
    date_range_ml: "ഏപ്രിൽ 20 - മേയ് 20",
    date_range_start: "April 20",
    date_range_end: "May 20",
    friendly_signs: ["Virgo", "Capricorn", "Cancer", "Pisces"],
    enemy_signs: ["Leo", "Aquarius"],
    day_association: "Monday",
    day_association_tr: "Pazartesi",
    night_association: "Friday",
    night_association_tr: "Cuma",
    letters: ["ج", "د"],
    letter_names: ["Jim", "Dal"],
    explanation_en: "The builder, provider, and stabilizer. Represents material security, patience, and sensuality.",
    explanation_ml: "നിർമ്മാതാവ്, നൽകുന്നവൻ, സ്ഥിരത വരുത്തുന്നവൻ. ഭൗതിക സുരക്ഷിതത്വം, ക്ഷമ, ഇന്ദ്രിയസുഖം എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  gemini: {
    key: "gemini",
    name_en: "Gemini",
    name_ml_equivalent: "മിഥുനം",
    name_tr: "İkizler",
    name_ar: "الجوزاء",
    name_en_transliteration: "Al-Jawza",
    name_ml_reading: "അൽ-ജൗസാഅ്",
    symbol: "♊",
    element: "Air",
    element_ml: "വായു",
    element_ar: "هواء",
    gender: "Masculine",
    gender_ml: "പുരുഷൻ",
    gender_ar: "ذكر",
    ruling_planet: "Mercury",
    ruling_planet_ml: "ബുധൻ",
    ruling_planet_ar: "عطارد",
    ruling_planet_symbol: "☿",
    metal: "Mercury",
    metal_ml: "മെർക്കുറി",
    metal_ar: "زئبق",
    incense: "Mastic & Frankincense",
    incense_ml: "മാസ്റ്റിക്കും കുന്തുരുക്കവും",
    incense_ar: "المصطكي واللبان",
    date_range: "May 21 - June 20",
    date_range_ml: "മേയ് 21 - ജൂൺ 20",
    date_range_start: "May 21",
    date_range_end: "June 20",
    friendly_signs: ["Libra", "Aquarius", "Aries", "Leo"],
    enemy_signs: ["Virgo", "Pisces"],
    day_association: "Wednesday",
    day_association_tr: "Çarşamba",
    night_association: "Thursday",
    night_association_tr: "Perşembe",
    letters: ["ه", "و"],
    letter_names: ["Ha", "Waw"],
    explanation_en: "The communicator, learner, and connector. Represents duality, intellect, and adaptability.",
    explanation_ml: "ആശയവിനിമയക്കാരൻ, പഠിതാവ്, ബന്ധിപ്പിക്കുന്നവൻ. ദ്വൈതത, ബുദ്ധി, പൊരുത്തപ്പെടൽ എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  cancer: {
    key: "cancer",
    name_en: "Cancer",
    name_ml_equivalent: "കർക്കിടകം",
    name_tr: "Yengeç",
    name_ar: "السرطان",
    name_en_transliteration: "Al-Saratan",
    name_ml_reading: "അൽ-സറത്വാന",
    symbol: "♋",
    element: "Water",
    element_ml: "വെള്ളം",
    element_ar: "ماء",
    gender: "Feminine",
    gender_ml: "സ്ത്രീ",
    gender_ar: "أنثى",
    ruling_planet: "Moon",
    ruling_planet_ml: "ചന്ദ്രൻ",
    ruling_planet_ar: "القمر",
    ruling_planet_symbol: "☽",
    metal: "Silver",
    metal_ml: "വെള്ളി",
    metal_ar: "فضة",
    incense: "Sandalwood & Rose",
    incense_ml: "ചന്ദനവും റോസും",
    incense_ar: "الصندل والورد",
    date_range: "June 21 - July 22",
    date_range_ml: "ജൂൺ 21 - ജൂലൈ 22",
    date_range_start: "June 21",
    date_range_end: "July 22",
    friendly_signs: ["Scorpio", "Pisces", "Taurus", "Virgo"],
    enemy_signs: ["Aries", "Libra"],
    day_association: "Monday",
    day_association_tr: "Pazartesi",
    night_association: "Tuesday",
    night_association_tr: "Salı",
    letters: ["ز", "ح"],
    letter_names: ["Zay", "Ha"],
    explanation_en: "The nurturer, protector, and empath. Represents emotions, family, and intuition.",
    explanation_ml: "പോഷിപ്പിക്കുന്നവൻ, സംരക്ഷകൻ, സഹാനുഭൂതിയുള്ളവൻ. വികാരങ്ങൾ, കുടുംബം, അന്തർജ്ഞാനം എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  leo: {
    key: "leo",
    name_en: "Leo",
    name_ml_equivalent: "ചിങ്ങം",
    name_tr: "Aslan",
    name_ar: "الأسد",
    name_en_transliteration: "Al-Asad",
    name_ml_reading: "അൽ-അസദ്",
    symbol: "♌",
    element: "Fire",
    element_ml: "അഗ്നി",
    element_ar: "نار",
    gender: "Masculine",
    gender_ml: "പുരുഷൻ",
    gender_ar: "ذكر",
    ruling_planet: "Sun",
    ruling_planet_ml: "സൂര്യൻ",
    ruling_planet_ar: "الشمس",
    ruling_planet_symbol: "☉",
    metal: "Gold",
    metal_ml: "പൊൻ",
    metal_ar: "ذهب",
    incense: "Oud & Mastic (Superior)",
    incense_ml: "ഊദും മാസ്റ്റിക്കും (മികച്ചത്)",
    incense_ar: "العود والمصطكي (متفوق)",
    date_range: "July 23 - August 22",
    date_range_ml: "ജൂലൈ 23 - ഓഗസ്റ്റ് 22",
    date_range_start: "July 23",
    date_range_end: "August 22",
    friendly_signs: ["Aries", "Sagittarius", "Gemini", "Libra"],
    enemy_signs: ["Taurus", "Aquarius"],
    day_association: "Sunday",
    day_association_tr: "Pazar",
    night_association: "Monday",
    night_association_tr: "Pazartesi",
    letters: ["ط", "ي"],
    letter_names: ["Ta", "Ya"],
    explanation_en: "The king, creator, and leader. Represents royalty, confidence, and self-expression.",
    explanation_ml: "രാജാവ്, സ്രഷ്ടാവ്, നേതാവ്. രാജകീയത, ആത്മവിശ്വാസം, സ്വയം പ്രകടനം എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  virgo: {
    key: "virgo",
    name_en: "Virgo",
    name_ml_equivalent: "കന്നി",
    name_tr: "Başak",
    name_ar: "العذراء",
    name_en_transliteration: "Al-Adhra",
    name_ml_reading: "അൽ-അദ്റാഅ്",
    symbol: "♍",
    element: "Earth",
    element_ml: "ഭൂമി",
    element_ar: "أرض",
    gender: "Feminine",
    gender_ml: "സ്ത്രീ",
    gender_ar: "أنثى",
    ruling_planet: "Mercury",
    ruling_planet_ml: "ബുധൻ",
    ruling_planet_ar: "عطارد",
    ruling_planet_symbol: "☿",
    metal: "Mercury",
    metal_ml: "മെർക്കുറി",
    metal_ar: "زئبق",
    incense: "Frankincense & Mastic",
    incense_ml: "കുന്തുരുക്കവും മാസ്റ്റിക്കും",
    incense_ar: "اللبان والمصطكي",
    date_range: "August 23 - September 22",
    date_range_ml: "ഓഗസ്റ്റ് 23 - സെപ്റ്റംബർ 22",
    date_range_start: "August 23",
    date_range_end: "September 22",
    friendly_signs: ["Taurus", "Capricorn", "Cancer", "Scorpio"],
    enemy_signs: ["Gemini", "Pisces"],
    day_association: "Wednesday",
    day_association_tr: "Çarşamba",
    night_association: "Thursday",
    night_association_tr: "Perşembe",
    letters: ["ك", "ل"],
    letter_names: ["Kaf", "Lam"],
    explanation_en: "The analyst, healer, and servant. Represents purity, precision, and practical service.",
    explanation_ml: "വിശകലനക്കാരൻ, ചികിത്സകൻ, സേവകൻ. ശുദ്ധി, കൃത്യത, പ്രായോഗിക സേവനം എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  libra: {
    key: "libra",
    name_en: "Libra",
    name_ml_equivalent: "തുലാം",
    name_tr: "Terazi",
    name_ar: "الميزان",
    name_en_transliteration: "Al-Mizan",
    name_ml_reading: "അൽ-മീസാൻ",
    symbol: "♎",
    element: "Air",
    element_ml: "വായു",
    element_ar: "هواء",
    gender: "Masculine",
    gender_ml: "പുരുഷൻ",
    gender_ar: "ذكر",
    ruling_planet: "Venus",
    ruling_planet_ml: "ശുക്രൻ",
    ruling_planet_ar: "الزهرة",
    ruling_planet_symbol: "♀",
    metal: "Copper",
    metal_ml: "ചെമ്പ്",
    metal_ar: "نحاس",
    incense: "Oud & Mastic (Balance)",
    incense_ml: "ഊദും മാസ്റ്റിക്കും (സന്തുലിതം)",
    incense_ar: "العود والمصطكي (توازن)",
    date_range: "September 23 - October 22",
    date_range_ml: "സെപ്റ്റംബർ 23 - ഒക്ടോബർ 22",
    date_range_start: "September 23",
    date_range_end: "October 22",
    friendly_signs: ["Gemini", "Aquarius", "Leo", "Sagittarius"],
    enemy_signs: ["Cancer", "Capricorn"],
    day_association: "Friday",
    day_association_tr: "Cuma",
    night_association: "Saturday",
    night_association_tr: "Cumartesi",
    letters: ["م", "ن"],
    letter_names: ["Mim", "Nun"],
    explanation_en: "The diplomat, harmonizer, and judge. Represents balance, justice, and partnership.",
    explanation_ml: "നയതന്ത്രജ്ഞൻ, സാമരസ്യക്കാരൻ, ന്യായാധിപൻ. സന്തുലിതാവസ്ഥ, നീതി, കൂട്ടാളിത്തം എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  scorpio: {
    key: "scorpio",
    name_en: "Scorpio",
    name_ml_equivalent: "വൃശ്ചികം",
    name_tr: "Akrep",
    name_ar: "العقرب",
    name_en_transliteration: "Al-Aqrab",
    name_ml_reading: "അൽ-അഖ്റബ്",
    symbol: "♏",
    element: "Water",
    element_ml: "വെള്ളം",
    element_ar: "ماء",
    gender: "Feminine",
    gender_ml: "സ്ത്രീ",
    gender_ar: "أنثى",
    ruling_planet: "Mars",
    ruling_planet_ml: "ചൊവ്വ",
    ruling_planet_ar: "المريخ",
    ruling_planet_symbol: "♂",
    metal: "Iron",
    metal_ml: "ഇരുമ്പ്",
    metal_ar: "حديد",
    incense: "Costus & Dragon's Blood",
    incense_ml: "കുസ്തും ഡ്രാഗൺസ് ബ്ലഡും",
    incense_ar: "القسط ودم التنين",
    date_range: "October 23 - November 21",
    date_range_ml: "ഒക്ടോബർ 23 - നവംബർ 21",
    date_range_start: "October 23",
    date_range_end: "November 21",
    friendly_signs: ["Cancer", "Pisces", "Virgo", "Capricorn"],
    enemy_signs: ["Leo", "Aquarius"],
    day_association: "Tuesday",
    day_association_tr: "Salı",
    night_association: "Wednesday",
    night_association_tr: "Çarşamba",
    letters: ["س", "ع"],
    letter_names: ["Sin", "Ayn"],
    explanation_en: "The transformer, mystic, and warrior. Represents death, rebirth, and hidden power.",
    explanation_ml: "പരിവർത്തനക്കാരൻ, രഹസ്യവാദി, യോദ്ധാവ്. മരണം, പുനർജനനം, മറഞ്ഞ ശക്തി എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  sagittarius: {
    key: "sagittarius",
    name_en: "Sagittarius",
    name_ml_equivalent: "ധനു",
    name_tr: "Yay",
    name_ar: "القوس",
    name_en_transliteration: "Al-Qaws",
    name_ml_reading: "അൽ-ഖൗസ്",
    symbol: "♐",
    element: "Fire",
    element_ml: "അഗ്നി",
    element_ar: "نار",
    gender: "Masculine",
    gender_ml: "പുരുഷൻ",
    gender_ar: "ذكر",
    ruling_planet: "Jupiter",
    ruling_planet_ml: "വ്യാഴം",
    ruling_planet_ar: "المشتري",
    ruling_planet_symbol: "♃",
    metal: "Tin",
    metal_ml: "ഈയം",
    metal_ar: "قصدير",
    incense: "Saffron & Mastic",
    incense_ml: "കുങ്കുമപ്പൂവും മാസ്റ്റിക്കും",
    incense_ar: "الزعفران والمصطكي",
    date_range: "November 22 - December 21",
    date_range_ml: "നവംബർ 22 - ഡിസംബർ 21",
    date_range_start: "November 22",
    date_range_end: "December 21",
    friendly_signs: ["Aries", "Leo", "Gemini", "Aquarius"],
    enemy_signs: ["Virgo", "Pisces"],
    day_association: "Thursday",
    day_association_tr: "Perşembe",
    night_association: "Friday",
    night_association_tr: "Cuma",
    letters: ["ف", "ص"],
    letter_names: ["Fa", "Sad"],
    explanation_en: "The explorer, philosopher, and teacher. Represents wisdom, travel, and spiritual expansion.",
    explanation_ml: "പര്യവേക്ഷകൻ, തത്വചിന്തകൻ, അധ്യാപകൻ. ജ്ഞാനം, യാത്ര, ആത്മിക വിപുലീകരണം എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  capricorn: {
    key: "capricorn",
    name_en: "Capricorn",
    name_ml_equivalent: "മകരം",
    name_tr: "Oğlak",
    name_ar: "الجدي",
    name_en_transliteration: "Al-Jady",
    name_ml_reading: "അൽ-ജദ്-യ",
    symbol: "♑",
    element: "Earth",
    element_ml: "ഭൂമി",
    element_ar: "أرض",
    gender: "Feminine",
    gender_ml: "സ്ത്രീ",
    gender_ar: "أنثى",
    ruling_planet: "Saturn",
    ruling_planet_ml: "ശനി",
    ruling_planet_ar: "زحل",
    ruling_planet_symbol: "♄",
    metal: "Lead",
    metal_ml: "ലീഡ്",
    metal_ar: "رصاص",
    incense: "Myrrh & Frankincense",
    incense_ml: "മുറയും കുന്തുരുക്കവും",
    incense_ar: "المر واللبان",
    date_range: "December 22 - January 19",
    date_range_ml: "ഡിസംബർ 22 - ജനുവരി 19",
    date_range_start: "December 22",
    date_range_end: "January 19",
    friendly_signs: ["Taurus", "Virgo", "Scorpio", "Pisces"],
    enemy_signs: ["Aries", "Cancer"],
    day_association: "Saturday",
    day_association_tr: "Cumartesi",
    night_association: "Sunday",
    night_association_tr: "Pazar",
    letters: ["ق", "ر"],
    letter_names: ["Qaf", "Ra"],
    explanation_en: "The architect, manager, and achiever. Represents discipline, ambition, and structure.",
    explanation_ml: "വാസ്തുവിദ്യാഭ്യന്തൻ, മാനേജർ, നേട്ടക്കാരൻ. ശിക്ഷണം, മഹത്വാകാംക്ഷ, ഘടന എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  aquarius: {
    key: "aquarius",
    name_en: "Aquarius",
    name_ml_equivalent: "കുംഭം",
    name_tr: "Kova",
    name_ar: "الدلو",
    name_en_transliteration: "Al-Dalw",
    name_ml_reading: "അൽ-ദൽവ്",
    symbol: "♒",
    element: "Air",
    element_ml: "വായു",
    element_ar: "هواء",
    gender: "Masculine",
    gender_ml: "പുരുഷൻ",
    gender_ar: "ذكر",
    ruling_planet: "Saturn",
    ruling_planet_ml: "ശനി",
    ruling_planet_ar: "زحل",
    ruling_planet_symbol: "♄",
    metal: "Lead",
    metal_ml: "ലീഡ്",
    metal_ar: "رصاص",
    incense: "Luban Zakaridir",
    incense_ml: "ലുബാൻ സക്കരിദീർ",
    incense_ar: "اللبان زكردير",
    date_range: "January 20 - February 18",
    date_range_ml: "ജനുവരി 20 - ഫെബ്രുവരി 18",
    date_range_start: "January 20",
    date_range_end: "February 18",
    friendly_signs: ["Gemini", "Libra", "Aries", "Sagittarius"],
    enemy_signs: ["Taurus", "Leo"],
    day_association: "Saturday",
    day_association_tr: "Cumartesi",
    night_association: "Wednesday",
    night_association_tr: "Çarşamba",
    letters: ["ش", "ت"],
    letter_names: ["Shin", "Ta"],
    explanation_en: "The innovator, humanitarian, and rebel. Represents originality, independence, and future vision.",
    explanation_ml: "നവീകർത്താവ്, മാനുഷികപ്രവർത്തകൻ, കലാപകാരി. മൗലികത, സ്വാതന്ത്ര്യം, ഭാവി ദർശനം എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  },
  pisces: {
    key: "pisces",
    name_en: "Pisces",
    name_ml_equivalent: "മീനം",
    name_tr: "Balık",
    name_ar: "الحوت",
    name_en_transliteration: "Al-Hut",
    name_ml_reading: "അൽ-ഹൂത്",
    symbol: "♓",
    element: "Water",
    element_ml: "വെള്ളം",
    element_ar: "ماء",
    gender: "Feminine",
    gender_ml: "സ്ത്രീ",
    gender_ar: "أنثى",
    ruling_planet: "Jupiter",
    ruling_planet_ml: "വ്യാഴം",
    ruling_planet_ar: "المشتري",
    ruling_planet_symbol: "♃",
    metal: "Tin",
    metal_ml: "ഈയം",
    metal_ar: "قصدير",
    incense: "Saffron & Rose",
    incense_ml: "കുങ്കുമപ്പൂവും റോസും",
    incense_ar: "الزعفران والورد",
    date_range: "February 19 - March 20",
    date_range_ml: "ഫെബ്രുവരി 19 - മാർച്ച് 20",
    date_range_start: "February 19",
    date_range_end: "March 20",
    friendly_signs: ["Cancer", "Scorpio", "Taurus", "Capricorn"],
    enemy_signs: ["Gemini", "Virgo"],
    day_association: "Thursday",
    day_association_tr: "Perşembe",
    night_association: "Tuesday",
    night_association_tr: "Salı",
    letters: ["ث", "خ"],
    letter_names: ["Tha", "Kha"],
    explanation_en: "The mystic, healer, and dreamer. Represents compassion, intuition, and spiritual dissolution.",
    explanation_ml: "രഹസ്യവാദി, ചികിത്സകൻ, സ്വപ്നം കാണുന്നവൻ. കരുണ, അന്തർജ്ഞാനം, ആത്മിക ലയിക്കൽ എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു."
  }
};

export function getZodiacSign(key) {
  return ZODIAC_SIGNS[key] || null;
}

export function getFriendlySigns(key) {
  const sign = ZODIAC_SIGNS[key];
  if (!sign) return [];
  return sign.friendly_signs;
}

export function getEnemySigns(key) {
  const sign = ZODIAC_SIGNS[key];
  if (!sign) return [];
  return sign.enemy_signs;
}

export function getZodiacByElement(element) {
  return Object.values(ZODIAC_SIGNS).filter(sign => sign.element === element);
}

export function getZodiacByDate(date) {
  const month = date.getMonth() + 1;
  const day = date.getDate();
  
  if ((month === 3 && day >= 21) || (month === 4 && day <= 19)) return ZODIAC_SIGNS.aries;
  if ((month === 4 && day >= 20) || (month === 5 && day <= 20)) return ZODIAC_SIGNS.taurus;
  if ((month === 5 && day >= 21) || (month === 6 && day <= 20)) return ZODIAC_SIGNS.gemini;
  if ((month === 6 && day >= 21) || (month === 7 && day <= 22)) return ZODIAC_SIGNS.cancer;
  if ((month === 7 && day >= 23) || (month === 8 && day <= 22)) return ZODIAC_SIGNS.leo;
  if ((month === 8 && day >= 23) || (month === 9 && day <= 22)) return ZODIAC_SIGNS.virgo;
  if ((month === 9 && day >= 23) || (month === 10 && day <= 22)) return ZODIAC_SIGNS.libra;
  if ((month === 10 && day >= 23) || (month === 11 && day <= 21)) return ZODIAC_SIGNS.scorpio;
  if ((month === 11 && day >= 22) || (month === 12 && day <= 21)) return ZODIAC_SIGNS.sagittarius;
  if ((month === 12 && day >= 22) || (month === 1 && day <= 19)) return ZODIAC_SIGNS.capricorn;
  if ((month === 1 && day >= 20) || (month === 2 && day <= 18)) return ZODIAC_SIGNS.aquarius;
  return ZODIAC_SIGNS.pisces;
}