// ═══════════════════════════════════════════════════════════════
// FAAL HASRATH — Independent Data
// Used ONLY by FaalHasrathPage. Zero shared logic with any module.
// ═══════════════════════════════════════════════════════════════

export const FAAL_CELLS = [
  {
    id: 1,
    symbol: "☀️",
    arabic: "الشمس",
    title: "The Sun — Al-Shams",
    description: "The radiant sun rises with full power. Light overcomes all darkness and doubt.",
    interpretation: "Your situation is illuminated. What was hidden will be revealed. A time of clarity and success is at hand.",
    guidance: "Move forward with confidence. The path ahead is clear. Share your light generously.",
  },
  {
    id: 2,
    symbol: "🌙",
    arabic: "القمر",
    title: "The Moon — Al-Qamar",
    description: "The moon governs the tides of the heart and the rhythms of the unseen world.",
    interpretation: "Hidden emotions and intuitions are at work. Patience and reflection are needed before action.",
    guidance: "Trust your inner voice. Do not rush. The answer will emerge when the time is right.",
  },
  {
    id: 3,
    symbol: "⭐",
    arabic: "النجم",
    title: "The Star — Al-Najm",
    description: "A guiding star appears above the horizon, pointing the way through the night.",
    interpretation: "Hope is alive. Guidance comes from a higher source. Your journey has divine direction.",
    guidance: "Follow your aspiration. Do not be swayed by doubt. The star never lies to the sincere traveler.",
  },
  {
    id: 4,
    symbol: "🔥",
    arabic: "النار",
    title: "The Fire — Al-Nār",
    description: "Sacred fire burns away impurities and transforms what it touches.",
    interpretation: "A trial or challenge is present — but it refines you. Passion and will are strong.",
    guidance: "Do not fear the heat. What is genuine cannot be consumed. You will emerge stronger.",
  },
  {
    id: 5,
    symbol: "💧",
    arabic: "الماء",
    title: "The Water — Al-Māʾ",
    description: "Pure water flows to the lowest place and nourishes all life without discrimination.",
    interpretation: "Gentleness and humility are your greatest tools now. Flow around obstacles, do not fight them.",
    guidance: "Be adaptable. Softness conquers hardness. Let go of rigid expectations.",
  },
  {
    id: 6,
    symbol: "🌬️",
    arabic: "الهواء",
    title: "The Wind — Al-Rīḥ",
    description: "The wind carries seeds and messages across great distances, invisible yet powerful.",
    interpretation: "News or change is coming. Something unseen is already in motion on your behalf.",
    guidance: "Remain open. What arrives on the wind may surprise you. Do not cling to old plans.",
  },
  {
    id: 7,
    symbol: "🌍",
    arabic: "الأرض",
    title: "The Earth — Al-Arḍ",
    description: "The earth bears all burdens without complaint and gives generously to those who work it.",
    interpretation: "Stability and foundation are the theme. Patience and steady effort will yield solid results.",
    guidance: "Root yourself. Build slowly and surely. Do not be distracted by fleeting temptations.",
  },
  {
    id: 8,
    symbol: "⚡",
    arabic: "البرق",
    title: "The Lightning — Al-Barq",
    description: "Lightning strikes with sudden brilliance, illuminating the entire sky in an instant.",
    interpretation: "A sudden insight or event will change everything. Speed and decisiveness are required.",
    guidance: "Act when the moment comes — do not hesitate. Opportunities like this pass in an instant.",
  },
  {
    id: 9,
    symbol: "🌊",
    arabic: "الموج",
    title: "The Wave — Al-Mawj",
    description: "Great waves carry ships to their destination or swallow those who resist the tide.",
    interpretation: "A powerful force is moving in your life. Resistance will exhaust you; cooperation will carry you.",
    guidance: "Align yourself with the greater movement. Surrender what you cannot control and ride what you can.",
  },
  {
    id: 10,
    symbol: "🌿",
    arabic: "الشجرة",
    title: "The Tree — Al-Shajara",
    description: "The tree with deep roots stands unshaken in every storm and provides shade for all.",
    interpretation: "Your roots — your values, your family, your faith — are your strength now. Return to them.",
    guidance: "Seek counsel from those with deep experience. Ground yourself before you reach upward.",
  },
  {
    id: 11,
    symbol: "🦅",
    arabic: "النسر",
    title: "The Eagle — Al-Nisr",
    description: "The eagle soars above all obstacles, seeing with unmatched clarity from great heights.",
    interpretation: "Elevate your perspective. What troubles you from below is small when seen from above.",
    guidance: "Rise above petty concerns. Think long-term. Your vision is your greatest power — use it.",
  },
  {
    id: 12,
    symbol: "🐍",
    arabic: "الحية",
    title: "The Serpent — Al-Ḥayya",
    description: "The serpent sheds its skin and renews itself — a symbol of transformation and wisdom.",
    interpretation: "A transformation is necessary. Something old must be released to allow new growth.",
    guidance: "Do not fear change. What you are shedding served its purpose. Embrace the new form emerging.",
  },
  {
    id: 13,
    symbol: "🕊️",
    arabic: "الحمامة",
    title: "The Dove — Al-Ḥamāma",
    description: "The dove carries the message of peace and heralds the end of difficulty.",
    interpretation: "Peace and reconciliation are available. A conflict can be resolved. Blessings approach.",
    guidance: "Extend forgiveness freely. Make the first gesture of peace. What returns to you will be beautiful.",
  },
  {
    id: 14,
    symbol: "⚓",
    arabic: "المرساة",
    title: "The Anchor — Al-Mirsāh",
    description: "The anchor holds the ship steady in turbulent waters, preventing it from being carried away.",
    interpretation: "You need to hold fast. Stability through principle will protect you. Do not drift.",
    guidance: "Identify what truly anchors you — faith, purpose, love — and hold to it. Ride out the storm.",
  },
  {
    id: 15,
    symbol: "🔑",
    arabic: "المفتاح",
    title: "The Key — Al-Miftāḥ",
    description: "A golden key appears — the answer to a locked door you have long been searching for.",
    interpretation: "A solution is within reach. The way is being opened. A door long closed will now unlock.",
    guidance: "Ask the right questions. Look for the simple answer, not the complicated one. The door is already opening.",
  },
  {
    id: 16,
    symbol: "💎",
    arabic: "الجوهرة",
    title: "The Jewel — Al-Jawhara",
    description: "A rare jewel formed under immense pressure — its beauty is the product of endurance.",
    interpretation: "The highest outcome. Your effort and patience have produced something precious and lasting.",
    guidance: "Treasure what you have built. Share your gifts wisely. This is a moment of completion and reward.",
  },
];