// ═══════════════════════════════════════════════════════════════
// FAALUL LUQMAN — Independent Dataset
// Used ONLY by FaalHasrathPage (Luqman subsection).
// Zero shared data with Faal Ali or Faal Hasrath.
// 28 cells, each with a unique Arabic symbol and its own result.
// ═══════════════════════════════════════════════════════════════

export const LUQMAN_CELLS = [
  {
    lq_id: 101,
    symbol: "ا",
    symbolName: "Alif",
    ml: {
      shortTitle: "ഉയർച്ച",
      result: "ഉയർച്ചയും ഉന്നതിയും",
      body: "ഈ ഫാൽ ഉത്തമമാണ്. ആഗ്രഹിക്കുന്ന കാര്യം സഫലമാകും. ഉദ്ദേശിക്കുന്ന യാത്ര ശുഭകരമാകും. ജീവിതത്തിൽ ഉയർച്ചയും മഹത്ത്വവും ലഭിക്കും.",
      remedy: "ദിവസവും ബിസ്മില്ല ചൊല്ലി കാര്യം ആരംഭിക്കുക.",
    },
    en: {
      shortTitle: "Rise & Elevation",
      result: "Rise and Elevation",
      body: "This omen is excellent. Desired matters will be fulfilled. Intended journeys will be auspicious. Elevation and honor are indicated in life.",
      remedy: "Begin every matter daily by reciting Bismillah.",
    },
  },
  {
    lq_id: 102,
    symbol: "ب",
    symbolName: "Ba",
    ml: {
      shortTitle: "ആനന്ദം",
      result: "സന്തോഷവും ആനന്ദവും",
      body: "കുടുംബത്തിൽ സന്തോഷം ഉണ്ടാകും. ആഗ്രഹങ്ങൾ നിറവേറും. ദുഃഖങ്ങൾ മാറിപ്പോകും. ധനലാഭം ഉണ്ടാകും.",
      remedy: "ദരിദ്രർക്ക് ഭക്ഷണം നൽകുക.",
    },
    en: {
      shortTitle: "Joy & Happiness",
      result: "Joy and Happiness",
      body: "Joy will come to the family. Wishes will be fulfilled. Sorrows will pass. Financial gain is indicated.",
      remedy: "Feed the poor.",
    },
  },
  {
    lq_id: 103,
    symbol: "ج",
    symbolName: "Jim",
    ml: {
      shortTitle: "സംഘർഷം",
      result: "തടസ്സങ്ങളും സംഘർഷങ്ങളും",
      body: "ഈ ഫാൽ ശുഭകരമല്ല. ശത്രുക്കളാൽ ഉപദ്രവം ഉണ്ടാകും. കാര്യം നടക്കാൻ കാലതാമസം ഉണ്ടാകും. ക്ഷമ ആവശ്യമാണ്.",
      remedy: "ആയത്തുൽ കുർസി ദിവസം നാൽപ്പതു വട്ടം ഓതുക.",
    },
    en: {
      shortTitle: "Obstacles Ahead",
      result: "Obstacles and Conflicts",
      body: "This omen is unfavorable. Harm from enemies may arise. Delays in achieving goals. Patience is required.",
      remedy: "Recite Ayatul Kursi forty times daily.",
    },
  },
  {
    lq_id: 104,
    symbol: "د",
    symbolName: "Dal",
    ml: {
      shortTitle: "നിരന്തര പ്രവർത്തനം",
      result: "ക്ഷമയോടെ മുന്നോട്ടു പോകുക",
      body: "കഠിനാദ്ധ്വാനത്തിന്റെ ഫലം ലഭിക്കും. ഉദ്ദേശ്യം നടക്കുമെങ്കിലും കാലതാമസം ഉണ്ടാകും. ശ്രമം ഉപേക്ഷിക്കരുത്.",
      remedy: "ഇസ്തിഗ്ഫാർ കൂടുതൽ ചൊല്ലുക.",
    },
    en: {
      shortTitle: "Persist Forward",
      result: "Proceed with Patience",
      body: "The fruits of hard work will come. The goal will be reached but with delay. Do not abandon effort.",
      remedy: "Recite Istighfar abundantly.",
    },
  },
  {
    lq_id: 105,
    symbol: "ه",
    symbolName: "Ha",
    ml: {
      shortTitle: "ദൈവാനുഗ്രഹം",
      result: "ദൈവാനുഗ്രഹം ലഭിക്കും",
      body: "ഉദ്ദേശിക്കുന്ന കാര്യം ഭംഗിയായി നടക്കും. ആരോഗ്യം ഭേദമാകും. ആഗ്രഹിക്കുന്ന വ്യക്തിയെ കണ്ടുമുട്ടും.",
      remedy: "സൂറത്ത് യൂനുസ് ഓതുക.",
    },
    en: {
      shortTitle: "Divine Grace",
      result: "Divine Grace Granted",
      body: "Intended matters will proceed beautifully. Health will improve. The desired person will be met.",
      remedy: "Recite Surah Yunus.",
    },
  },
  {
    lq_id: 106,
    symbol: "و",
    symbolName: "Waw",
    ml: {
      shortTitle: "ഐക്യം",
      result: "ഐക്യവും സൗഹൃദവും",
      body: "ബന്ധങ്ങൾ ശക്തമാകും. വേർപ്പെട്ടവർ ഒന്നിക്കും. കലഹങ്ങൾ മാറും. മനഃശാന്തി ലഭിക്കും.",
      remedy: "ഒരു ദരിദ്ര കുടുംബത്തെ സഹായിക്കുക.",
    },
    en: {
      shortTitle: "Unity & Bond",
      result: "Unity and Friendship",
      body: "Relationships will strengthen. Separated ones will reunite. Conflicts will resolve. Peace of mind will be attained.",
      remedy: "Help a needy family.",
    },
  },
  {
    lq_id: 107,
    symbol: "ز",
    symbolName: "Zayn",
    ml: {
      shortTitle: "അലഞ്ഞുതിരിയൽ",
      result: "ആശയക്കുഴപ്പം",
      body: "ഒരു കാര്യത്തിലും ഉറച്ചു നിൽക്കാൻ ബുദ്ധിമുട്ടുണ്ടാകും. തീരുമാനമെടുക്കൽ പ്രയാസം. ഒരു ആലിമിനോട് ഉപദേശം ചോദിക്കുക.",
      remedy: "സൂറത്ത് ഇഖ്ലാസ് ഇരുനൂറ് തവണ ഓതി ദുആ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Confusion",
      result: "Confusion and Uncertainty",
      body: "Difficulty in staying firm on any matter. Decision-making will be hard. Seek advice from a scholar.",
      remedy: "Recite Surah Ikhlas two hundred times and supplicate.",
    },
  },
  {
    lq_id: 108,
    symbol: "ح",
    symbolName: "Ha (heavy)",
    ml: {
      shortTitle: "ഗുണകരം",
      result: "ഫാൽ ഗുണകരമാണ്",
      body: "യാത്ര ശുഭകരം. ജോലിയിൽ ഉന്നതി ഉണ്ടാകും. ധനം ലഭിക്കും. ബന്ധുക്കളിൽ നിന്ന് സഹായം ലഭിക്കും.",
      remedy: "നഫിൽ നിസ്കാരം നിർവഹിക്കുക.",
    },
    en: {
      shortTitle: "Beneficial",
      result: "This Omen is Beneficial",
      body: "Travel is auspicious. Promotion at work is indicated. Wealth will arrive. Help from relatives will come.",
      remedy: "Perform voluntary prayers.",
    },
  },
  {
    lq_id: 109,
    symbol: "ط",
    symbolName: "Tta",
    ml: {
      shortTitle: "ശക്തി",
      result: "ശക്തിയും ധൈര്യവും",
      body: "ശത്രുക്കളെ തോൽപ്പിക്കും. ആഗ്രഹം നടക്കും. ഭൂമി, സ്വത്ത് സംബന്ധമായ കാര്യങ്ങൾ അനുകൂലമാകും.",
      remedy: "ദൈനംദിനം ദുറൂദ് ഓതുക.",
    },
    en: {
      shortTitle: "Strength",
      result: "Strength and Courage",
      body: "Enemies will be overcome. Desire will be fulfilled. Matters related to land and property will become favorable.",
      remedy: "Recite Durood daily.",
    },
  },
  {
    lq_id: 110,
    symbol: "ي",
    symbolName: "Ya",
    ml: {
      shortTitle: "ദീർഘദൃഷ്ടി",
      result: "ജ്ഞാനവും ദീർഘദൃഷ്ടിയും",
      body: "ഇൽമ്, ജ്ഞാനം, കല എന്നിവയിൽ വിജയം ഉണ്ടാകും. പഠനകാര്യങ്ങൾ ഭംഗിയായി നടക്കും. ശിഷ്യഗണം ഉണ്ടാകും.",
      remedy: "ഒരു അനാഥ കുട്ടിക്ക് ഭക്ഷണം നൽകുക.",
    },
    en: {
      shortTitle: "Wisdom",
      result: "Wisdom and Foresight",
      body: "Success in knowledge, wisdom and arts is indicated. Studies will proceed well. Followers and students will come.",
      remedy: "Feed an orphaned child.",
    },
  },
  {
    lq_id: 111,
    symbol: "ك",
    symbolName: "Kaf",
    ml: {
      shortTitle: "കൃപ",
      result: "അല്ലാഹുവിന്റെ കൃപ",
      body: "ആഗ്രഹങ്ങൾ സഫലമാകും. ബുദ്ധിമുട്ടുകൾ ദൂരെ മാറും. ആരോഗ്യകരമായ ജീവിതം ഉണ്ടാകും.",
      remedy: "ദിവസേന ഒരു ജുസ്ഉ് ഖുർആൻ ഓതുക.",
    },
    en: {
      shortTitle: "Mercy",
      result: "Mercy of Allah",
      body: "Desires will be fulfilled. Difficulties will go away. A healthy life is indicated.",
      remedy: "Recite one Juz of the Quran daily.",
    },
  },
  {
    lq_id: 112,
    symbol: "ل",
    symbolName: "Lam",
    ml: {
      shortTitle: "ദൂരത്ത്",
      result: "ദൂരയാത്ര ഫലകരം",
      body: "ദൂരദേശത്ത് നിന്ന് നല്ല വാർത്ത ലഭിക്കും. ദേശഭ്രഷ്ടനായ ആൾ തിരിച്ചുവരും. ദൂരെ ഉള്ള ബന്ധങ്ങൾ ഊഷ്മളമാകും.",
      remedy: "ഖബ്ർ സിയാറത്ത് ചെയ്ത് ദുആ ചെയ്യുക.",
    },
    en: {
      shortTitle: "From Afar",
      result: "Long-Distance Journey is Fruitful",
      body: "Good news from distant lands will arrive. An exile will return. Distant relationships will warm again.",
      remedy: "Visit a grave and supplicate.",
    },
  },
  {
    lq_id: 113,
    symbol: "م",
    symbolName: "Mim",
    ml: {
      shortTitle: "സ്നേഹം",
      result: "സ്നേഹവും കരുതലും",
      body: "വൈവാഹിക ജീവിതം ശുഭകരം. പ്രേമകാര്യങ്ങൾ നടക്കും. കുടുംബ ഐക്യം ഉണ്ടാകും. ഗർഭിണിക്ക് ഗുണം.",
      remedy: "മൂന്ന് ദിവസം നോമ്പ് അനുഷ്ഠിക്കുക.",
    },
    en: {
      shortTitle: "Love & Care",
      result: "Love and Affection",
      body: "Married life is favorable. Romantic matters will succeed. Family harmony is indicated. Favorable for expectant mothers.",
      remedy: "Observe a fast for three days.",
    },
  },
  {
    lq_id: 114,
    symbol: "ن",
    symbolName: "Nun",
    ml: {
      shortTitle: "ഗ്രഹണം",
      result: "ക്ഷണികമായ ബുദ്ധിമുട്ടുകൾ",
      body: "തൽക്കാലം ബുദ്ധിമുട്ടുകൾ ഉണ്ടാകും. ഭയം ഉണ്ടാകാം. ക്ഷമ പാലിക്കുക; പ്രകാശം ഉദിക്കും.",
      remedy: "സൂറത്ത് ദുഹ ഓതി ദുആ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Temporary Hardship",
      result: "Temporary Difficulties",
      body: "Temporary difficulties will arise. Fear may be felt. Maintain patience; light will emerge.",
      remedy: "Recite Surah Ad-Duha and supplicate.",
    },
  },
  {
    lq_id: 115,
    symbol: "س",
    symbolName: "Sin",
    ml: {
      shortTitle: "ശാന്തി",
      result: "മനഃശാന്തിയും സമൃദ്ധിയും",
      body: "ജീവിതത്തിൽ ശാന്തി ഉണ്ടാകും. ബിസിനസ്സ് വിജയകരം. ശ്രമം ഫലം കാണും. ആത്മീയ ഉയർച്ച ഉണ്ടാകും.",
      remedy: "ദരിദ്രർക്ക് വസ്ത്രം ദാനം ചെയ്യുക.",
    },
    en: {
      shortTitle: "Peace & Prosperity",
      result: "Peace of Mind and Prosperity",
      body: "Peace will enter life. Business will be successful. Efforts will bear fruit. Spiritual elevation is indicated.",
      remedy: "Donate clothing to the poor.",
    },
  },
  {
    lq_id: 116,
    symbol: "ع",
    symbolName: "Ain",
    ml: {
      shortTitle: "ഉൾക്കാഴ്ച",
      result: "ആഴത്തിലുള്ള ഉൾക്കാഴ്ച",
      body: "ഒളിഞ്ഞ സത്യങ്ങൾ വെളിവാകും. ദ്രോഹം ചെയ്തവർ തിരിച്ചറിഞ്ഞ് ക്ഷമ ചോദിക്കും. നീതി ലഭിക്കും.",
      remedy: "ഖുർആൻ ഒരു ഖത്മ് ഓതി ഹദ്‌യ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Insight",
      result: "Deep Insight",
      body: "Hidden truths will be revealed. Those who wronged will recognize and seek forgiveness. Justice will be obtained.",
      remedy: "Complete a Khatm of the Quran and dedicate the reward.",
    },
  },
  {
    lq_id: 117,
    symbol: "ف",
    symbolName: "Fa",
    ml: {
      shortTitle: "വിജയം",
    result: "ഫത്ഹ് — വിജയം",
      body: "എല്ലാ കാര്യത്തിലും വിജയം ഉണ്ടാകും. ഉദ്ദേശ്യം സഫലമാകും. ദ്വാരം തുറക്കപ്പെടും.",
      remedy: "ശുക്കർ നമ്പർ സദഖ നൽകുക.",
    },
    en: {
      shortTitle: "Victory",
      result: "Fath — Victory",
      body: "Success in all matters will come. Purpose will be fulfilled. Doors will be opened.",
      remedy: "Give gratitude charity.",
    },
  },
  {
    lq_id: 118,
    symbol: "ص",
    symbolName: "Swad",
    ml: {
      shortTitle: "ക്ഷമ",
      result: "ക്ഷമ — പ്രതിഫലം ലഭിക്കും",
      body: "ക്ഷമയുള്ളവർക്ക് മഹത്തായ ഫലം ഉണ്ടാകും. ഇപ്പോൾ ബുദ്ധിമുട്ടുകൾ ഉണ്ടെങ്കിലും ഭാവി ശോഭനം.",
      remedy: "നോമ്പ് അനുഷ്ഠിക്കുക. ഇസ്ലാഹ് ഗ്രന്ഥങ്ങൾ വായിക്കുക.",
    },
    en: {
      shortTitle: "Patience Rewarded",
      result: "Patience — Reward Will Come",
      body: "Great reward awaits the patient. Though current difficulties exist, the future is bright.",
      remedy: "Observe fasts and read books of spiritual reform.",
    },
  },
  {
    lq_id: 119,
    symbol: "ق",
    symbolName: "Qaf",
    ml: {
      shortTitle: "ആദ്ധ്യാത്മികത",
      result: "ആത്മീയ ഉന്നതി",
      body: "ആദ്ധ്യാത്മിക ജീവിതം ഉന്നതമാകും. ഔലിയാക്കളുടെ ബർകത്ത് ലഭിക്കും. ഹൃദയ ശുദ്ധി ഉണ്ടാകും.",
      remedy: "ഒരു ഔലിയായുടെ ദർഗ്ഗ സിയാറത്ത് ചെയ്യുക.",
    },
    en: {
      shortTitle: "Spirituality",
      result: "Spiritual Elevation",
      body: "Spiritual life will elevate. Blessings of the saints will be received. Purity of heart is indicated.",
      remedy: "Visit the shrine of a saint.",
    },
  },
  {
    lq_id: 120,
    symbol: "ر",
    symbolName: "Ra",
    ml: {
      shortTitle: "ദൂതർ",
      result: "ശുഭ സന്ദേശം ലഭിക്കും",
      body: "ദൂരത്ത് നിന്ന് ശുഭ സന്ദേശം ഉടൻ ലഭിക്കും. ദീർഘ കാലത്തേ ആഗ്രഹം ഇപ്പോൾ സഫലമാകും.",
      remedy: "രണ്ട് റക്അത്ത് ഹാജത്ത് നിസ്കാരം നിർവഹിക്കുക.",
    },
    en: {
      shortTitle: "Good Message",
      result: "A Good Message Will Arrive",
      body: "A good message from afar will arrive soon. A long-cherished wish will now be fulfilled.",
      remedy: "Perform two units of the prayer of need (Salatul Hajah).",
    },
  },
  {
    lq_id: 121,
    symbol: "ش",
    symbolName: "Shin",
    ml: {
      shortTitle: "ചിതറൽ",
      result: "ശ്രദ്ധ വ്യതിചലിക്കരുത്",
      body: "ഒന്നിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കാൻ ബുദ്ധിമുട്ടുണ്ടാകും. ഒരേ സമയം പലതും ചെയ്യാൻ ശ്രമിക്കുന്നത് ദോഷകരം.",
      remedy: "സൂറത്ത് ഫലഖ്, നാസ് ദിവസേന ഓതുക.",
    },
    en: {
      shortTitle: "Scattered Focus",
      result: "Do Not Let Attention Scatter",
      body: "Difficulty in concentrating on one thing will arise. Attempting many things at once may bring harm.",
      remedy: "Recite Surah Al-Falaq and An-Nas daily.",
    },
  },
  {
    lq_id: 122,
    symbol: "ت",
    symbolName: "Ta",
    ml: {
      shortTitle: "ആരോഗ്യം",
      result: "ആരോഗ്യ ലാഭം",
      body: "രോഗം ശമിക്കും. ശരീരത്തിന് ശക്തി ഉണ്ടാകും. ദീർഘകാല അസുഖം ഭേദമാകും.",
      remedy: "ഏഴ് ദിവസം കൂൾ ഓതി വെള്ളത്തിൽ ഊതി കുടിക്കുക.",
    },
    en: {
      shortTitle: "Health Recovery",
      result: "Recovery of Health",
      body: "Illness will heal. The body will gain strength. A long-standing ailment will be cured.",
      remedy: "Recite Al-Fatiha for seven days, blow into water, and drink.",
    },
  },
  {
    lq_id: 123,
    symbol: "ث",
    symbolName: "Tha",
    ml: {
      shortTitle: "ഉറപ്പ്",
      result: "ഉറച്ചു നിൽക്കുക",
      body: "ബുദ്ധിമുട്ടുകൾ ഉണ്ടെങ്കിലും ഉറച്ചു നിൽക്കുന്നവർക്ക് വിജയം ഉണ്ടാകും. ഉദ്ദേശ്യം ഉപേക്ഷിക്കരുത്.",
      remedy: "ഇസ്ലാഹ് ഗ്രന്ഥം വായിക്കുക.",
    },
    en: {
      shortTitle: "Stay Firm",
      result: "Stand Firm",
      body: "Despite difficulties, those who remain firm will succeed. Do not abandon your purpose.",
      remedy: "Read a book of spiritual guidance.",
    },
  },
  {
    lq_id: 124,
    symbol: "خ",
    symbolName: "Kha",
    ml: {
      shortTitle: "ഗോപ്യം",
      result: "ഗോപ്യ കാര്യങ്ങൾ",
      body: "ഒളിഞ്ഞ ശത്രുക്കൾ ഉണ്ടാകും. വിവരം ചോർന്നുപോകും. സൂക്ഷ്മതയോടെ ഇടപ്പെടുക.",
      remedy: "ഖസ്ബ് ഓതി അഭയം തേടുക.",
    },
    en: {
      shortTitle: "Hidden Dangers",
      result: "Hidden Matters",
      body: "Hidden enemies may be present. Information may leak. Deal with caution.",
      remedy: "Recite protective prayers and seek refuge.",
    },
  },
  {
    lq_id: 125,
    symbol: "ذ",
    symbolName: "Dhal",
    ml: {
      shortTitle: "ഓർമ്മ",
      result: "അനുഭവങ്ങളിൽ നിന്ന് പഠിക്കുക",
      body: "ഭൂതകാലം ഓർമ്മിക്കുക. ആവർത്തിക്കപ്പെടുന്ന തെറ്റുകൾ ഒഴിവാക്കുക. ഭൂതകാലം ഭാവിക്ക് വഴികാട്ടും.",
      remedy: "ഒരാഴ്ച ദിനരാത്ര ദിക്ർ ചൊല്ലുക.",
    },
    en: {
      shortTitle: "Learn from Past",
      result: "Learn from Experiences",
      body: "Remember the past. Avoid repeating mistakes. The past will guide the future.",
      remedy: "Engage in Dhikr morning and evening for one week.",
    },
  },
  {
    lq_id: 126,
    symbol: "ض",
    symbolName: "Dhwad",
    ml: {
      shortTitle: "നഷ്ടം",
      result: "ഭൗതിക നഷ്ടം",
      body: "ധനനഷ്ടം ഉണ്ടാകും. ഭൗതിക സ്വത്ത് ഏതെങ്കിലും ദോഷം നേരിടും. ഉടൻ ദുആ ചെയ്യുക.",
      remedy: "ഉടൻ സദഖ ചെയ്ത് ദോഷ നിവൃത്തി ചോദിക്കുക.",
    },
    en: {
      shortTitle: "Material Loss",
      result: "Material Loss Indicated",
      body: "Financial loss may occur. Material property may face some harm. Supplicate immediately.",
      remedy: "Immediately give charity and seek removal of harm.",
    },
  },
  {
    lq_id: 127,
    symbol: "ظ",
    symbolName: "Dha",
    ml: {
      shortTitle: "അനീതി",
      result: "അനീതിക്ക് ഉത്തരം ലഭിക്കും",
      body: "അനീതി ചെയ്തവർ ശിക്ഷിക്കപ്പെടും. ക്ഷമ പാലിക്കുക; നീതി ഉടൻ ലഭിക്കും.",
      remedy: "മസ്ജിദിൽ ഇഅ്തിക്കാഫ് ഇരിക്കുക.",
    },
    en: {
      shortTitle: "Justice Comes",
      result: "Answer to Injustice Will Come",
      body: "Those who acted unjustly will be held accountable. Stay patient; justice will come soon.",
      remedy: "Perform I'tikaf in the mosque.",
    },
  },
  {
    lq_id: 128,
    symbol: "غ",
    symbolName: "Ghain",
    ml: {
      shortTitle: "ഗൈബ്",
      result: "അദൃശ്യ സഹായം",
      body: "അദൃശ്യ സ്ഥാനത്ത് നിന്ന് സഹായം ലഭിക്കും. ഒരിക്കലും ആഗ്രഹം ഉപേക്ഷിക്കരുത്. അല്ലാഹുവിന്റെ ഗൈബ് ഭണ്ഡാരം അനന്തമാണ്.",
      remedy: "ഒരു ആഴ്ച ഓരോ ദിവസവും 99 ഇസ്മ് ജബ്ർ ചൊല്ലി ദുആ ചെയ്യുക.",
    },
    en: {
      shortTitle: "Unseen Help",
      result: "Help from the Unseen",
      body: "Help will come from an unseen source. Never abandon hope. The treasuries of Allah are infinite.",
      remedy: "Recite Ya Jabbar 99 times daily for one week and supplicate.",
    },
  },
];