// ═══════════════════════════════════════════════════════════════
// FAAL HASRATH — Independent Data
// Used ONLY by FaalHasrathPage. Zero shared logic with any module.
// 16 unique traditional symbols — each fixed to its own meaning.
// ═══════════════════════════════════════════════════════════════

export const FAAL_CELLS = [
  {
    id: 1,
    symbol: "☀",
    arabic: "الشمس",
    title: "The Sun — Al-Shams",
    description: "The radiant sun rises with full power. Light overcomes all darkness and doubt.",
    interpretation: "Your situation is illuminated. What was hidden will be revealed. A time of clarity and success is at hand.",
    advice: "Step forward boldly. The light is on your side — act while clarity is strong.",
  },
  {
    id: 2,
    symbol: "☽",
    arabic: "القمر",
    title: "The Moon — Al-Qamar",
    description: "The moon governs the tides of the heart and the rhythms of the unseen world.",
    interpretation: "Hidden emotions and intuitions are at work. Patience and reflection are needed before action.",
    advice: "Observe, do not react. The right moment reveals itself when you are still.",
  },
  {
    id: 3,
    symbol: "★",
    arabic: "النجم",
    title: "The Star — Al-Najm",
    description: "A guiding star appears above the horizon, pointing the way through the night.",
    interpretation: "Hope is alive. Guidance comes from a higher source. Your journey has divine direction.",
    advice: "Hold to your aspiration. Let no doubt extinguish your inner star.",
  },
  {
    id: 4,
    symbol: "🜂",
    arabic: "النار",
    title: "The Fire — Al-Nār",
    description: "Sacred fire burns away impurities and transforms what it touches.",
    interpretation: "A trial or challenge is present — but it refines you. Passion and will are strong.",
    advice: "Do not shy from difficulty. The fire that tests you is the same fire that forges you.",
  },
  {
    id: 5,
    symbol: "🜄",
    arabic: "الماء",
    title: "The Water — Al-Māʾ",
    description: "Pure water flows to the lowest place and nourishes all life without discrimination.",
    interpretation: "Gentleness and humility are your greatest tools now. Flow around obstacles, do not fight them.",
    advice: "Release rigidity. Soften your approach and the way will open of its own accord.",
  },
  {
    id: 6,
    symbol: "🜁",
    arabic: "الهواء",
    title: "The Wind — Al-Rīḥ",
    description: "The wind carries seeds and messages across great distances, invisible yet powerful.",
    interpretation: "News or change is coming. Something unseen is already in motion on your behalf.",
    advice: "Stay open and light. Cling to nothing and you will be carried to exactly where you need to be.",
  },
  {
    id: 7,
    symbol: "🜃",
    arabic: "الأرض",
    title: "The Earth — Al-Arḍ",
    description: "The earth bears all burdens without complaint and gives generously to those who work it.",
    interpretation: "Stability and foundation are the theme. Patience and steady effort will yield solid results.",
    advice: "Plant your effort and water it daily. The harvest belongs to the patient.",
  },
  {
    id: 8,
    symbol: "⚡",
    arabic: "البرق",
    title: "The Lightning — Al-Barq",
    description: "Lightning strikes with sudden brilliance, illuminating the entire sky in an instant.",
    interpretation: "A sudden insight or event will change everything. Speed and decisiveness are required.",
    advice: "When the moment arrives, act without hesitation. Lightning waits for no one.",
  },
  {
    id: 9,
    symbol: "☿",
    arabic: "عطارد",
    title: "Mercury — ʿUṭārid",
    description: "The messenger planet governs intellect, communication, and swift movement between worlds.",
    interpretation: "Your mind and words carry the power of transformation now. A message or negotiation is key.",
    advice: "Speak with precision and listen with full attention. The right words open closed doors.",
  },
  {
    id: 10,
    symbol: "♃",
    arabic: "المشتري",
    title: "Jupiter — Al-Mushtarī",
    description: "Jupiter, greatest of the celestial bodies, bestows expansion, wisdom, and divine favor.",
    interpretation: "Good fortune and growth are available to you. An opportunity larger than expected is approaching.",
    advice: "Think expansively. Accept generosity when it is offered. Do not limit the blessing before it arrives.",
  },
  {
    id: 11,
    symbol: "♄",
    arabic: "زحل",
    title: "Saturn — Zuḥal",
    description: "Saturn is the planet of discipline, time, and the great teacher who demands mastery before reward.",
    interpretation: "Effort and perseverance are being tested. The outcome depends on how seriously you have prepared.",
    advice: "Return to discipline. Cut what is unnecessary. What you build with patience will last a lifetime.",
  },
  {
    id: 12,
    symbol: "♀",
    arabic: "الزهرة",
    title: "Venus — Al-Zuhra",
    description: "Venus governs love, beauty, harmony, and the magnetic attraction between souls.",
    interpretation: "A matter of the heart, beauty, or harmony is at the center of your situation.",
    advice: "Lead with warmth and sincerity. What you seek in another, first cultivate within yourself.",
  },
  {
    id: 13,
    symbol: "♂",
    arabic: "المريخ",
    title: "Mars — Al-Mirrīkh",
    description: "Mars is the warrior planet — courage, decisive force, and the will to conquer obstacles.",
    interpretation: "Strength and courage are called for. A direct confrontation or decisive action cannot be avoided.",
    advice: "Be brave but not reckless. Channel your force with clear intention, not blind aggression.",
  },
  {
    id: 14,
    symbol: "⊕",
    arabic: "الصليب",
    title: "The Cross of the Earth",
    description: "The four-quartered circle unites the four directions, four elements, and the meeting of heaven and earth.",
    interpretation: "You stand at a crossroads. Four paths diverge — the choice you make now defines your future.",
    advice: "Pause before choosing. Consult your deepest values, then commit fully to the path you select.",
  },
  {
    id: 15,
    symbol: "🔑",
    arabic: "المفتاح",
    title: "The Key — Al-Miftāḥ",
    description: "A golden key appears — the answer to a locked door you have long been searching for.",
    interpretation: "A solution is within reach. The way is being opened. A door long closed will now unlock.",
    advice: "Look for the simple answer within the complex problem. The key was never far from the lock.",
  },
  {
    id: 16,
    symbol: "◈",
    arabic: "الجوهرة",
    title: "The Jewel — Al-Jawhara",
    description: "A rare jewel formed under immense pressure — its beauty is the product of endurance.",
    interpretation: "The highest outcome. Your effort and patience have produced something precious and lasting.",
    advice: "Receive this completion with gratitude. What you have forged through hardship is yours to keep forever.",
  },
];