// ═══════════════════════════════════════════════════════════════
// MAGICAL HOLY NAMES DATABASE
// Completely independent module — no shared logic with any other module.
// ═══════════════════════════════════════════════════════════════

export const HOLY_NAMES = [
  { id: 1,  arabicName: "الله",              arabicHarakat: "اللَّه",              englishName: "Allah",               abjadValue: 66,   letterCount: 4  },
  { id: 2,  arabicName: "الرحمن",            arabicHarakat: "الرَّحْمَن",          englishName: "Al-Rahman",           abjadValue: 298,  letterCount: 6  },
  { id: 3,  arabicName: "الرحيم",            arabicHarakat: "الرَّحِيم",           englishName: "Al-Raheem",           abjadValue: 258,  letterCount: 6  },
  { id: 4,  arabicName: "الملك",             arabicHarakat: "الْمَلِك",            englishName: "Al-Malik",            abjadValue: 90,   letterCount: 5  },
  { id: 5,  arabicName: "القدوس",            arabicHarakat: "الْقُدُّوس",          englishName: "Al-Quddus",           abjadValue: 170,  letterCount: 6  },
  { id: 6,  arabicName: "السلام",            arabicHarakat: "السَّلَام",           englishName: "Al-Salam",            abjadValue: 131,  letterCount: 6  },
  { id: 7,  arabicName: "المؤمن",            arabicHarakat: "الْمُؤْمِن",          englishName: "Al-Mu'min",           abjadValue: 137,  letterCount: 6  },
  { id: 8,  arabicName: "المهيمن",           arabicHarakat: "الْمُهَيْمِن",        englishName: "Al-Muhaymin",         abjadValue: 145,  letterCount: 7  },
  { id: 9,  arabicName: "العزيز",            arabicHarakat: "الْعَزِيز",           englishName: "Al-Aziz",             abjadValue: 94,   letterCount: 6  },
  { id: 10, arabicName: "الجبار",            arabicHarakat: "الْجَبَّار",          englishName: "Al-Jabbar",           abjadValue: 206,  letterCount: 6  },
  { id: 11, arabicName: "المتكبر",           arabicHarakat: "الْمُتَكَبِّر",       englishName: "Al-Mutakabbir",       abjadValue: 662,  letterCount: 7  },
  { id: 12, arabicName: "الخالق",            arabicHarakat: "الْخَالِق",           englishName: "Al-Khaliq",           abjadValue: 731,  letterCount: 6  },
  { id: 13, arabicName: "البارئ",            arabicHarakat: "الْبَارِئ",           englishName: "Al-Bari",             abjadValue: 214,  letterCount: 5  },
  { id: 14, arabicName: "المصور",            arabicHarakat: "الْمُصَوِّر",         englishName: "Al-Musawwir",         abjadValue: 336,  letterCount: 6  },
  { id: 15, arabicName: "الغفار",            arabicHarakat: "الْغَفَّار",          englishName: "Al-Ghaffar",          abjadValue: 1281, letterCount: 6  },
  { id: 16, arabicName: "القهار",            arabicHarakat: "الْقَهَّار",          englishName: "Al-Qahhar",           abjadValue: 306,  letterCount: 6  },
  { id: 17, arabicName: "الوهاب",            arabicHarakat: "الْوَهَّاب",          englishName: "Al-Wahhab",           abjadValue: 14,   letterCount: 6  },
  { id: 18, arabicName: "الرزاق",            arabicHarakat: "الرَّزَّاق",          englishName: "Al-Razzaq",           abjadValue: 308,  letterCount: 6  },
  { id: 19, arabicName: "الفتاح",            arabicHarakat: "الْفَتَّاح",          englishName: "Al-Fattah",           abjadValue: 489,  letterCount: 6  },
  { id: 20, arabicName: "العليم",            arabicHarakat: "الْعَلِيم",           englishName: "Al-Alim",             abjadValue: 150,  letterCount: 6  },
  { id: 21, arabicName: "القابض",            arabicHarakat: "الْقَابِض",           englishName: "Al-Qabid",            abjadValue: 903,  letterCount: 6  },
  { id: 22, arabicName: "الباسط",            arabicHarakat: "الْبَاسِط",           englishName: "Al-Basit",            abjadValue: 72,   letterCount: 6  },
  { id: 23, arabicName: "الخافض",            arabicHarakat: "الْخَافِض",           englishName: "Al-Khafid",           abjadValue: 1481, letterCount: 6  },
  { id: 24, arabicName: "الرافع",            arabicHarakat: "الرَّافِع",           englishName: "Al-Rafi",             abjadValue: 351,  letterCount: 5  },
  { id: 25, arabicName: "المعز",             arabicHarakat: "الْمُعِزّ",           englishName: "Al-Mu'izz",           abjadValue: 117,  letterCount: 5  },
  { id: 26, arabicName: "المذل",             arabicHarakat: "الْمُذِلّ",           englishName: "Al-Mudhill",          abjadValue: 770,  letterCount: 5  },
  { id: 27, arabicName: "السميع",            arabicHarakat: "السَّمِيع",           englishName: "Al-Sami",             abjadValue: 180,  letterCount: 6  },
  { id: 28, arabicName: "البصير",            arabicHarakat: "الْبَصِير",           englishName: "Al-Basir",            abjadValue: 302,  letterCount: 6  },
  { id: 29, arabicName: "الحكم",             arabicHarakat: "الْحَكَم",            englishName: "Al-Hakam",            abjadValue: 68,   letterCount: 5  },
  { id: 30, arabicName: "العدل",             arabicHarakat: "الْعَدْل",            englishName: "Al-Adl",              abjadValue: 104,  letterCount: 5  },
  { id: 31, arabicName: "اللطيف",            arabicHarakat: "اللَّطِيف",           englishName: "Al-Latif",            abjadValue: 129,  letterCount: 6  },
  { id: 32, arabicName: "الخبير",            arabicHarakat: "الْخَبِير",           englishName: "Al-Khabir",           abjadValue: 812,  letterCount: 6  },
  { id: 33, arabicName: "الحليم",            arabicHarakat: "الْحَلِيم",           englishName: "Al-Halim",            abjadValue: 88,   letterCount: 6  },
  { id: 34, arabicName: "العظيم",            arabicHarakat: "الْعَظِيم",           englishName: "Al-Azim",             abjadValue: 1020, letterCount: 6  },
  { id: 35, arabicName: "الغفور",            arabicHarakat: "الْغَفُور",           englishName: "Al-Ghafur",           abjadValue: 1286, letterCount: 6  },
  { id: 36, arabicName: "الشكور",            arabicHarakat: "الشَّكُور",           englishName: "Al-Shakur",           abjadValue: 526,  letterCount: 6  },
  { id: 37, arabicName: "العلي",             arabicHarakat: "الْعَلِيّ",           englishName: "Al-Ali",              abjadValue: 110,  letterCount: 5  },
  { id: 38, arabicName: "الكبير",            arabicHarakat: "الْكَبِير",           englishName: "Al-Kabir",            abjadValue: 232,  letterCount: 6  },
  { id: 39, arabicName: "الحفيظ",            arabicHarakat: "الْحَفِيظ",           englishName: "Al-Hafiz",            abjadValue: 998,  letterCount: 6  },
  { id: 40, arabicName: "المقيت",            arabicHarakat: "الْمُقِيت",           englishName: "Al-Muqit",            abjadValue: 550,  letterCount: 6  },
  { id: 41, arabicName: "الحسيب",            arabicHarakat: "الْحَسِيب",           englishName: "Al-Hasib",            abjadValue: 80,   letterCount: 6  },
  { id: 42, arabicName: "الجليل",            arabicHarakat: "الْجَلِيل",           englishName: "Al-Jalil",            abjadValue: 73,   letterCount: 6  },
  { id: 43, arabicName: "الكريم",            arabicHarakat: "الْكَرِيم",           englishName: "Al-Karim",            abjadValue: 270,  letterCount: 6  },
  { id: 44, arabicName: "الرقيب",            arabicHarakat: "الرَّقِيب",           englishName: "Al-Raqib",            abjadValue: 312,  letterCount: 6  },
  { id: 45, arabicName: "المجيب",            arabicHarakat: "الْمُجِيب",           englishName: "Al-Mujib",            abjadValue: 55,   letterCount: 6  },
  { id: 46, arabicName: "الواسع",            arabicHarakat: "الْوَاسِع",           englishName: "Al-Wasi",             abjadValue: 137,  letterCount: 6  },
  { id: 47, arabicName: "الحكيم",            arabicHarakat: "الْحَكِيم",           englishName: "Al-Hakim",            abjadValue: 78,   letterCount: 6  },
  { id: 48, arabicName: "الودود",            arabicHarakat: "الْوَدُود",           englishName: "Al-Wadud",            abjadValue: 20,   letterCount: 6  },
  { id: 49, arabicName: "المجيد",            arabicHarakat: "الْمَجِيد",           englishName: "Al-Majid",            abjadValue: 57,   letterCount: 6  },
  { id: 50, arabicName: "الباعث",            arabicHarakat: "الْبَاعِث",           englishName: "Al-Ba'ith",           abjadValue: 573,  letterCount: 6  },
  { id: 51, arabicName: "الشهيد",            arabicHarakat: "الشَّهِيد",           englishName: "Al-Shahid",           abjadValue: 319,  letterCount: 6  },
  { id: 52, arabicName: "الحق",              arabicHarakat: "الْحَقّ",             englishName: "Al-Haqq",             abjadValue: 108,  letterCount: 4  },
  { id: 53, arabicName: "الوكيل",            arabicHarakat: "الْوَكِيل",           englishName: "Al-Wakil",            abjadValue: 66,   letterCount: 6  },
  { id: 54, arabicName: "القوي",             arabicHarakat: "الْقَوِيّ",           englishName: "Al-Qawi",             abjadValue: 116,  letterCount: 5  },
  { id: 55, arabicName: "المتين",            arabicHarakat: "الْمَتِين",           englishName: "Al-Matin",            abjadValue: 500,  letterCount: 6  },
  { id: 56, arabicName: "الولي",             arabicHarakat: "الْوَلِيّ",           englishName: "Al-Wali",             abjadValue: 46,   letterCount: 5  },
  { id: 57, arabicName: "الحميد",            arabicHarakat: "الْحَمِيد",           englishName: "Al-Hamid",            abjadValue: 62,   letterCount: 6  },
  { id: 58, arabicName: "المحصي",            arabicHarakat: "الْمُحْصِي",          englishName: "Al-Muhsi",            abjadValue: 148,  letterCount: 6  },
  { id: 59, arabicName: "المبدئ",            arabicHarakat: "الْمُبْدِئ",          englishName: "Al-Mubdi",            abjadValue: 56,   letterCount: 6  },
  { id: 60, arabicName: "المعيد",            arabicHarakat: "الْمُعِيد",           englishName: "Al-Mu'id",            abjadValue: 124,  letterCount: 6  },
  { id: 61, arabicName: "المحيي",            arabicHarakat: "الْمُحْيِي",          englishName: "Al-Muhyi",            abjadValue: 68,   letterCount: 6  },
  { id: 62, arabicName: "المميت",            arabicHarakat: "الْمُمِيت",           englishName: "Al-Mumit",            abjadValue: 490,  letterCount: 6  },
  { id: 63, arabicName: "الحي",              arabicHarakat: "الْحَيّ",             englishName: "Al-Hayy",             abjadValue: 18,   letterCount: 4  },
  { id: 64, arabicName: "القيوم",            arabicHarakat: "الْقَيُّوم",          englishName: "Al-Qayyum",           abjadValue: 156,  letterCount: 6  },
  { id: 65, arabicName: "الواجد",            arabicHarakat: "الْوَاجِد",           englishName: "Al-Wajid",            abjadValue: 14,   letterCount: 6  },
  { id: 66, arabicName: "الماجد",            arabicHarakat: "الْمَاجِد",           englishName: "Al-Majid (Al-Maji)", abjadValue: 48,   letterCount: 6  },
  { id: 67, arabicName: "الواحد",            arabicHarakat: "الْوَاحِد",           englishName: "Al-Wahid",            abjadValue: 19,   letterCount: 6  },
  { id: 68, arabicName: "الأحد",             arabicHarakat: "الْأَحَد",            englishName: "Al-Ahad",             abjadValue: 13,   letterCount: 4  },
  { id: 69, arabicName: "الصمد",             arabicHarakat: "الصَّمَد",            englishName: "Al-Samad",            abjadValue: 134,  letterCount: 5  },
  { id: 70, arabicName: "القادر",            arabicHarakat: "الْقَادِر",           englishName: "Al-Qadir",            abjadValue: 305,  letterCount: 6  },
  { id: 71, arabicName: "المقتدر",           arabicHarakat: "الْمُقْتَدِر",        englishName: "Al-Muqtadir",         abjadValue: 744,  letterCount: 7  },
  { id: 72, arabicName: "المقدم",            arabicHarakat: "الْمُقَدِّم",         englishName: "Al-Muqaddim",         abjadValue: 184,  letterCount: 6  },
  { id: 73, arabicName: "المؤخر",            arabicHarakat: "الْمُؤَخِّر",         englishName: "Al-Mu'akhkhir",       abjadValue: 846,  letterCount: 6  },
  { id: 74, arabicName: "الأول",             arabicHarakat: "الْأَوَّل",           englishName: "Al-Awwal",            abjadValue: 37,   letterCount: 5  },
  { id: 75, arabicName: "الآخر",             arabicHarakat: "الْآخِر",             englishName: "Al-Akhir",            abjadValue: 801,  letterCount: 5  },
  { id: 76, arabicName: "الظاهر",            arabicHarakat: "الظَّاهِر",           englishName: "Al-Zahir",            abjadValue: 1106, letterCount: 6  },
  { id: 77, arabicName: "الباطن",            arabicHarakat: "الْبَاطِن",           englishName: "Al-Batin",            abjadValue: 62,   letterCount: 6  },
  { id: 78, arabicName: "الوالي",            arabicHarakat: "الْوَالِي",           englishName: "Al-Wali",             abjadValue: 47,   letterCount: 6  },
  { id: 79, arabicName: "المتعالي",          arabicHarakat: "الْمُتَعَالِي",       englishName: "Al-Muta'ali",         abjadValue: 551,  letterCount: 8  },
  { id: 80, arabicName: "البر",              arabicHarakat: "الْبَرّ",             englishName: "Al-Barr",             abjadValue: 202,  letterCount: 4  },
  { id: 81, arabicName: "التواب",            arabicHarakat: "التَّوَّاب",          englishName: "Al-Tawwab",           abjadValue: 409,  letterCount: 6  },
  { id: 82, arabicName: "المنتقم",           arabicHarakat: "الْمُنْتَقِم",        englishName: "Al-Muntaqim",         abjadValue: 630,  letterCount: 7  },
  { id: 83, arabicName: "العفو",             arabicHarakat: "الْعَفُوّ",           englishName: "Al-Afuww",            abjadValue: 156,  letterCount: 5  },
  { id: 84, arabicName: "الرؤوف",            arabicHarakat: "الرَّؤُوف",           englishName: "Al-Ra'uf",            abjadValue: 286,  letterCount: 5  },
  { id: 85, arabicName: "مالك الملك",        arabicHarakat: "مَالِك الْمُلْك",     englishName: "Malik Al-Mulk",       abjadValue: 212,  letterCount: 9  },
  { id: 86, arabicName: "ذو الجلال والإكرام",arabicHarakat: "ذُو الْجَلَالِ وَالْإِكْرَام", englishName: "Dhul-Jalal Wal-Ikram", abjadValue: 1100, letterCount: 14 },
  { id: 87, arabicName: "المقسط",            arabicHarakat: "الْمُقْسِط",          englishName: "Al-Muqsit",           abjadValue: 209,  letterCount: 6  },
  { id: 88, arabicName: "الجامع",            arabicHarakat: "الْجَامِع",           englishName: "Al-Jami",             abjadValue: 114,  letterCount: 6  },
  { id: 89, arabicName: "الغني",             arabicHarakat: "الْغَنِيّ",           englishName: "Al-Ghani",            abjadValue: 1060, letterCount: 5  },
  { id: 90, arabicName: "المغني",            arabicHarakat: "الْمُغْنِي",          englishName: "Al-Mughni",           abjadValue: 1100, letterCount: 6  },
  { id: 91, arabicName: "المانع",            arabicHarakat: "الْمَانِع",           englishName: "Al-Mani",             abjadValue: 161,  letterCount: 6  },
  { id: 92, arabicName: "الضار",             arabicHarakat: "الضَّارّ",            englishName: "Al-Darr",             abjadValue: 1001, letterCount: 5  },
  { id: 93, arabicName: "النافع",            arabicHarakat: "النَّافِع",           englishName: "Al-Nafi",             abjadValue: 201,  letterCount: 6  },
  { id: 94, arabicName: "النور",             arabicHarakat: "النُّور",             englishName: "Al-Nur",              abjadValue: 256,  letterCount: 5  },
  { id: 95, arabicName: "الهادي",            arabicHarakat: "الْهَادِي",           englishName: "Al-Hadi",             abjadValue: 20,   letterCount: 6  },
  { id: 96, arabicName: "البديع",            arabicHarakat: "الْبَدِيع",           englishName: "Al-Badi",             abjadValue: 86,   letterCount: 6  },
  { id: 97, arabicName: "الباقي",            arabicHarakat: "الْبَاقِي",           englishName: "Al-Baqi",             abjadValue: 113,  letterCount: 5  },
  { id: 98, arabicName: "الوارث",            arabicHarakat: "الْوَارِث",           englishName: "Al-Warith",           abjadValue: 707,  letterCount: 6  },
  { id: 99, arabicName: "الرشيد",            arabicHarakat: "الرَّشِيد",           englishName: "Al-Rashid",           abjadValue: 514,  letterCount: 6  },
  { id: 100, arabicName: "الصبور",           arabicHarakat: "الصَّبُور",           englishName: "Al-Sabur",            abjadValue: 298,  letterCount: 6  },
];

export const MHN_CATEGORIES = [
  { id: "all",    label: "All" },
  { id: "low",    label: "Low (≤200)" },
  { id: "medium", label: "Medium (201-600)" },
  { id: "high",   label: "High (>600)" },
];