// ═══════════════════════════════════════════════════════════════
// METHOD 3 — ASMA-UL HUSNA WITH ADAD (INDEPENDENT DATABASE)
// ─────────────────────────────────────────────────────────────
// Source: "Asma ul Husna with Adad" reference table (Allah → As-Sabur).
// Exact Arabic spelling, exact ordering, exact Adad/Abjad value as
// supplied in the reference — used ONLY by Method 3.
// This database is completely independent from Method 1 / Method 2.
// ═══════════════════════════════════════════════════════════════
export const METHOD3_ASMA_UL_HUSNA_ADAD = [
  { name: "الله",                  translit: "Allah",            adad: 66 },
  { name: "الرحمن",                translit: "Ar-Rahman",        adad: 298 },
  { name: "الرحيم",                translit: "Ar-Rahim",         adad: 258 },
  { name: "الملك",                 translit: "Al-Malik",         adad: 90 },
  { name: "القدوس",                translit: "Al-Quddus",        adad: 170 },
  { name: "السلام",                translit: "As-Salam",         adad: 131 },
  { name: "المؤمن",                translit: "Al-Mu'min",        adad: 136 },
  { name: "المهيمن",               translit: "Al-Muhaymin",      adad: 145 },
  { name: "العزيز",                translit: "Al-Aziz",          adad: 94 },
  { name: "الجبار",                translit: "Al-Jabbar",        adad: 206 },
  { name: "المتكبر",               translit: "Al-Mutakabbir",    adad: 662 },
  { name: "الخالق",                translit: "Al-Khaliq",        adad: 731 },
  { name: "الباري",                translit: "Al-Bari'",         adad: 213 },
  { name: "المصور",                translit: "Al-Musawwir",      adad: 336 },
  { name: "الغفار",                translit: "Al-Ghaffar",       adad: 1281 },
  { name: "القهار",                translit: "Al-Qahhar",        adad: 306 },
  { name: "الوهاب",                translit: "Al-Wahhab",        adad: 14 },
  { name: "الرزاق",                translit: "Ar-Razzaq",        adad: 308 },
  { name: "الفتاح",                translit: "Al-Fattah",        adad: 489 },
  { name: "العليم",                translit: "Al-'Alim",         adad: 150 },
  { name: "القابض",                translit: "Al-Qabid",         adad: 903 },
  { name: "الباسط",                translit: "Al-Basit",         adad: 72 },
  { name: "الخافض",                translit: "Al-Khafid",        adad: 1481 },
  { name: "الرافع",                translit: "Ar-Rafi",          adad: 351 },
  { name: "المعز",                 translit: "Al-Mu'izz",        adad: 117 },
  { name: "المذل",                 translit: "Al-Mudhill",       adad: 770 },
  { name: "السميع",                translit: "As-Sami",          adad: 180 },
  { name: "البصير",                translit: "Al-Basir",         adad: 302 },
  { name: "الحكم",                 translit: "Al-Hakam",         adad: 68 },
  { name: "العدل",                 translit: "Al-'Adl",          adad: 104 },
  { name: "اللطيف",                translit: "Al-Latif",         adad: 129 },
  { name: "الخبير",                translit: "Al-Khabir",        adad: 812 },
  { name: "الحليم",                translit: "Al-Halim",         adad: 88 },
  { name: "العظيم",                translit: "Al-Azim",          adad: 1020 },
  { name: "الغفور",                translit: "Al-Ghafur",        adad: 1286 },
  { name: "الشكور",                translit: "Ash-Shakur",       adad: 526 },
  { name: "العلي",                 translit: "Al-Ali",           adad: 110 },
  { name: "الكبير",                translit: "Al-Kabir",         adad: 232 },
  { name: "الحفيظ",                translit: "Al-Hafiz",         adad: 998 },
  { name: "المقيت",                translit: "Al-Muqit",         adad: 550 },
  { name: "الحسيب",                translit: "Al-Hasib",         adad: 80 },
  { name: "الجليل",                translit: "Al-Jalil",         adad: 73 },
  { name: "الكريم",                translit: "Al-Karim",         adad: 270 },
  { name: "الرقيب",                translit: "Ar-Raqib",         adad: 312 },
  { name: "المجيب",                translit: "Al-Mujib",         adad: 55 },
  { name: "الواسع",                translit: "Al-Wasi",          adad: 137 },
  { name: "الحكيم",                translit: "Al-Hakim",         adad: 78 },
  { name: "الودود",                translit: "Al-Wadud",         adad: 20 },
  { name: "المجيد",                translit: "Al-Majid",         adad: 57 },
  { name: "الباعث",                translit: "Al-Ba'ith",        adad: 573 },
  { name: "الشهيد",                translit: "Ash-Shahid",       adad: 319 },
  { name: "الحق",                  translit: "Al-Haqq",          adad: 108 },
  { name: "الوكيل",                translit: "Al-Wakil",         adad: 66 },
  { name: "القوي",                 translit: "Al-Qawiyy",        adad: 116 },
  { name: "المتين",                translit: "Al-Matin",         adad: 500 },
  { name: "الولي",                 translit: "Al-Waliyy",        adad: 46 },
  { name: "الحميد",                translit: "Al-Hamid",         adad: 62 },
  { name: "المحصي",                translit: "Al-Muhsi",         adad: 148 },
  { name: "المبدئ",                translit: "Al-Mubdi'",        adad: 56 },
  { name: "المعيد",                translit: "Al-Mu'id",         adad: 124 },
  { name: "المحيي",                translit: "Al-Muhyi",         adad: 68 },
  { name: "المميت",                translit: "Al-Mumit",         adad: 490 },
  { name: "الحي",                  translit: "Al-Hayy",          adad: 18 },
  { name: "القيوم",                translit: "Al-Qayyum",        adad: 156 },
  { name: "الواجد",                translit: "Al-Wajid",         adad: 14 },
  { name: "الماجد",                translit: "Al-Majid",         adad: 48 },
  { name: "الواحد",                translit: "Al-Wahid",         adad: 19 },
  { name: "الصمد",                 translit: "As-Samad",         adad: 134 },
  { name: "القادر",                translit: "Al-Qadir",         adad: 305 },
  { name: "المقتدر",               translit: "Al-Muqtadir",      adad: 744 },
  { name: "المقدم",                translit: "Al-Muqaddim",      adad: 184 },
  { name: "المؤخر",                translit: "Al-Mu'akhkhir",    adad: 846 },
  { name: "الأول",                 translit: "Al-Awwal",         adad: 37 },
  { name: "الآخر",                 translit: "Al-Akhir",         adad: 801 },
  { name: "الظاهر",                translit: "Az-Zahir",         adad: 1106 },
  { name: "الباطن",                translit: "Al-Batin",         adad: 62 },
  { name: "الوالي",                translit: "Al-Wali",          adad: 47 },
  { name: "المتعالي",              translit: "Al-Muta'ali",      adad: 551 },
  { name: "البر",                  translit: "Al-Barr",          adad: 202 },
  { name: "التواب",                translit: "At-Tawwab",        adad: 409 },
  { name: "المنتقم",               translit: "Al-Muntaqim",      adad: 430 },
  { name: "العفو",                 translit: "Al-'Afuww",        adad: 156 },
  { name: "الرؤوف",                translit: "Ar-Ra'uf",         adad: 286 },
  { name: "مالك الملك",            translit: "Malik-al-Mulk",    adad: 212 },
  { name: "ذو الجلال والإكرام",    translit: "Dhu-al-Jalal wa-al-Ikram", adad: 1100 },
  { name: "المقسط",                translit: "Al-Muqsit",        adad: 209 },
  { name: "الجامع",                translit: "Al-Jami'",         adad: 114 },
  { name: "الغني",                 translit: "Al-Ghani",         adad: 1060 },
  { name: "المغني",                translit: "Al-Mughni",        adad: 1100 },
  { name: "المعطي",                translit: "Al-Mu'ti",         adad: 129 },
  { name: "المانع",                translit: "Al-Mani'",         adad: 161 },
  { name: "الضار",                 translit: "Ad-Darr",          adad: 1001 },
  { name: "النافع",                translit: "An-Nafi'",         adad: 201 },
  { name: "النور",                 translit: "An-Nur",           adad: 256 },
  { name: "الهادي",                translit: "Al-Hadi",          adad: 20 },
  { name: "البديع",                translit: "Al-Badi",          adad: 86 },
  { name: "الباقي",                translit: "Al-Baqi",          adad: 113 },
  { name: "الوارث",                translit: "Al-Warith",        adad: 707 },
  { name: "الرشيد",                translit: "Ar-Rashid",        adad: 614 },
  { name: "الصبور",                translit: "As-Sabur",         adad: 298 },
];