// ═══════════════════════════════════════════════════════════════
// METHOD 3 — ASMA-UL HUSNA WITH ADAD (INDEPENDENT DATABASE)
// ─────────────────────────────────────────────────────────────
// Source: "Asma ul Husna with Adad" reference table (Allah → As-Sabur).
// Exact Arabic spelling, exact ordering, exact Adad/Abjad value as
// supplied in the reference — used ONLY by Method 3.
// This database is completely independent from Method 1 / Method 2.
// ═══════════════════════════════════════════════════════════════
export const METHOD3_ASMA_UL_HUSNA_ADAD = [
  { name: "الله",                  adad: 66 },
  { name: "الرحمن",                adad: 298 },
  { name: "الرحيم",                adad: 258 },
  { name: "الملك",                 adad: 90 },
  { name: "القدوس",                adad: 170 },
  { name: "السلام",                adad: 131 },
  { name: "المؤمن",                adad: 136 },
  { name: "المهيمن",               adad: 145 },
  { name: "العزيز",                adad: 94 },
  { name: "الجبار",                adad: 206 },
  { name: "المتكبر",               adad: 662 },
  { name: "الخالق",                adad: 731 },
  { name: "الباري",                adad: 213 },
  { name: "المصور",                adad: 336 },
  { name: "الغفار",                adad: 1281 },
  { name: "القهار",                adad: 306 },
  { name: "الوهاب",                adad: 14 },
  { name: "الرزاق",                adad: 308 },
  { name: "الفتاح",                adad: 489 },
  { name: "العليم",                adad: 150 },
  { name: "القابض",                adad: 903 },
  { name: "الباسط",                adad: 72 },
  { name: "الخافض",                adad: 1481 },
  { name: "الرافع",                adad: 351 },
  { name: "المعز",                 adad: 117 },
  { name: "المذل",                 adad: 770 },
  { name: "السميع",                adad: 180 },
  { name: "البصير",                adad: 302 },
  { name: "الحكم",                 adad: 68 },
  { name: "العدل",                 adad: 104 },
  { name: "اللطيف",                adad: 129 },
  { name: "الخبير",                adad: 812 },
  { name: "الحليم",                adad: 88 },
  { name: "العظيم",                adad: 1020 },
  { name: "الغفور",                adad: 1286 },
  { name: "الشكور",                adad: 526 },
  { name: "العلي",                 adad: 110 },
  { name: "الكبير",                adad: 232 },
  { name: "الحفيظ",                adad: 998 },
  { name: "المقيت",                adad: 550 },
  { name: "الحسيب",                adad: 80 },
  { name: "الجليل",                adad: 73 },
  { name: "الكريم",                adad: 270 },
  { name: "الرقيب",                adad: 312 },
  { name: "المجيب",                adad: 55 },
  { name: "الواسع",                adad: 137 },
  { name: "الحكيم",                adad: 78 },
  { name: "الودود",                adad: 20 },
  { name: "المجيد",                adad: 57 },
  { name: "الباعث",                adad: 573 },
  { name: "الشهيد",                adad: 319 },
  { name: "الحق",                  adad: 108 },
  { name: "الوكيل",                adad: 66 },
  { name: "القوي",                 adad: 116 },
  { name: "المتين",                adad: 500 },
  { name: "الولي",                 adad: 46 },
  { name: "الحميد",                adad: 62 },
  { name: "المحصي",                adad: 148 },
  { name: "المبدئ",                adad: 56 },
  { name: "المعيد",                adad: 124 },
  { name: "المحيي",                adad: 68 },
  { name: "المميت",                adad: 490 },
  { name: "الحي",                  adad: 18 },
  { name: "القيوم",                adad: 156 },
  { name: "الواجد",                adad: 14 },
  { name: "الماجد",                adad: 48 },
  { name: "الواحد",                adad: 19 },
  { name: "الصمد",                 adad: 134 },
  { name: "القادر",                adad: 305 },
  { name: "المقتدر",               adad: 744 },
  { name: "المقدم",                adad: 184 },
  { name: "المؤخر",                adad: 846 },
  { name: "الأول",                 adad: 37 },
  { name: "الآخر",                 adad: 801 },
  { name: "الظاهر",                adad: 1106 },
  { name: "الباطن",                adad: 62 },
  { name: "الوالي",                adad: 47 },
  { name: "المتعالي",              adad: 551 },
  { name: "البر",                  adad: 202 },
  { name: "التواب",                adad: 409 },
  { name: "المنتقم",               adad: 430 },
  { name: "العفو",                 adad: 156 },
  { name: "الرؤوف",                adad: 286 },
  { name: "مالك الملك",            adad: 212 },
  { name: "ذو الجلال والإكرام",    adad: 1100 },
  { name: "المقسط",                adad: 209 },
  { name: "الجامع",                adad: 114 },
  { name: "الغني",                 adad: 1060 },
  { name: "المغني",                adad: 1100 },
  { name: "المعطي",                adad: 129 },
  { name: "المانع",                adad: 161 },
  { name: "الضار",                 adad: 1001 },
  { name: "النافع",                adad: 201 },
  { name: "النور",                 adad: 256 },
  { name: "الهادي",                adad: 20 },
  { name: "البديع",                adad: 86 },
  { name: "الباقي",                adad: 113 },
  { name: "الوارث",                adad: 707 },
  { name: "الرشيد",                adad: 614 },
  { name: "الصبور",                adad: 298 },
];