import { PLANTS_DATA_2 } from './plantsData2.js';

// ═══════════════════════════════════════════════════════════════
// PLANTS & INGREDIENTS DICTIONARY — STANDALONE DATA
// Schema: ArabicName, EnglishName, MalayalamName, ScientificName,
//         DescriptionEnglish, DescriptionMalayalam,
//         UsesEnglish, UsesMalayalam, PageReference, SourcePage
// Completely isolated. Zero imports from any engine or lib file.
// ═══════════════════════════════════════════════════════════════

export const PLANT_CATEGORIES = [
  { id: 'all',    label: 'All',     arabic: 'الكل',     ml: 'എല്ലാം' },
  { id: 'herb',   label: 'Herbs',   arabic: 'الأعشاب',  ml: 'ഔഷധസസ്യം' },
  { id: 'spice',  label: 'Spices',  arabic: 'التوابل',  ml: 'സുഗന്ധദ്രവ്യം' },
  { id: 'resin',  label: 'Resins',  arabic: 'الصمغ',    ml: 'റെസിൻ' },
  { id: 'root',   label: 'Roots',   arabic: 'الجذور',   ml: 'വേര്' },
  { id: 'flower', label: 'Flowers', arabic: 'الأزهار',  ml: 'പൂക്കൾ' },
  { id: 'fruit',  label: 'Fruits',  arabic: 'الفواكه',  ml: 'ഫലം' },
  { id: 'seed',   label: 'Seeds',   arabic: 'البذور',   ml: 'വിത്ത്' },
  { id: 'oil',    label: 'Oils',    arabic: 'الزيوت',   ml: 'എണ്ണ' },
  { id: 'wood',   label: 'Woods',   arabic: 'الأخشاب',  ml: 'മരം' },
  { id: 'other',  label: 'Other',   arabic: 'أخرى',     ml: 'മറ്റുള്ളവ' },
];

export const PLANTS_DATA = [
  {
    id: 1,
    category: 'resin',
    ArabicName: 'العقاقيه',
    EnglishName: 'Acacia',
    MalayalamName: 'അക്കേഷ്യ',
    ScientificName: 'Acacia Senegal',
    DescriptionEnglish: 'A gum resin used medicinally to soothe irritated areas of the digestive tract. Boiled down and evaporated into an astringent medicine to stop excessive mucous discharge and hemorrhages. Later discovered to serve as a binder for medicinal pellets.',
    DescriptionMalayalam: 'ദഹനേന്ദ്രിയ ഭാഗങ്ങളിലെ ജ്വലനം ശമിപ്പിക്കാൻ ഉപയോഗിക്കുന്ന ഗം റെസിൻ. അമിതമായ ശ്ലേഷ്മ സ്രാവവും രക്തസ്രാവവും നിർത്തുന്ന ഔഷധം ഉണ്ടാക്കാൻ ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Soothing digestive tract irritations; astringent for mucous discharge and hemorrhages; binder for medicinal pellets.',
    UsesMalayalam: 'ദഹനവ്യവസ്ഥ ശമനം; ശ്ലേഷ്മ, രക്തസ്രാവ നിയന്ത്രണം; ഔഷധ ഗുളിക ബൈൻഡർ.',
    PageReference: '23r-2',
    SourcePage: 193,
  },
  {
    id: 2,
    category: 'other',
    ArabicName: 'الحموضة',
    EnglishName: 'Acidic',
    MalayalamName: 'അമ്ലം',
    ScientificName: '',
    DescriptionEnglish: 'Refers to acidic substances added to medicines. Used to moisten the mouth and palate, to reduce acidity in the yellow bile and to prevent harm to the intestinal tract, whose nature was considered to be cold, dry and sinewy.',
    DescriptionMalayalam: 'മരുന്നുകളിൽ ചേർക്കുന്ന അമ്ല പദാർഥങ്ങൾ. വായും അണ്ണാക്കും നനയ്ക്കാനും മഞ്ഞ പിത്തത്തിലെ അമ്ലത കുറയ്ക്കാനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Moisten the mouth and palate; reduce acidity in yellow bile; prevent harm to the intestinal tract.',
    UsesMalayalam: 'വായ്, അണ്ണാക്ക് നനവ്; മഞ്ഞ പിത്ത അമ്ലത കുറക്കൽ; കുടൽ സംരക്ഷണം.',
    PageReference: '25r-16',
    SourcePage: 193,
  },
  {
    id: 3,
    category: 'wood',
    ArabicName: 'عود',
    EnglishName: 'Agar Wood',
    MalayalamName: 'അഗർവുഡ്',
    ScientificName: 'Aquilera malaccensis',
    DescriptionEnglish: 'An aromatic wood known as aloe wood or agar wood. Appears on pages 7r and 4r-15. Used in fumigations.',
    DescriptionMalayalam: 'ആലൂ മരം അല്ലെങ്കിൽ അഗർ മരം എന്നറിയപ്പെടുന്ന സുഗന്ധ മരം. ധൂപ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Used in fumigations.',
    UsesMalayalam: 'ധൂപ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    PageReference: '7r, 4r-15',
    SourcePage: 193,
  },
  {
    id: 4,
    category: 'herb',
    ArabicName: 'الفصفصا',
    EnglishName: 'Alfalfa',
    MalayalamName: 'അൽഫൽഫ',
    ScientificName: 'Medicago Satina',
    DescriptionEnglish: 'Appears on page 11v-13. Used in a tea to calm nerve endings, relieving the pain of arthritis and neuralgia. Also used to treat diseases of malnutrition or weight loss.',
    DescriptionMalayalam: 'നാഡി അഗ്രങ്ങൾ ശാന്തമാക്കാൻ ചായ രൂപത്തിൽ ഉപയോഗിക്കുന്നു. സന്ധിവാതം, നാഡീ വേദന ഒഴിവാക്കാൻ ഫലപ്രദം.',
    UsesEnglish: 'Tea to calm nerve endings; relieve arthritis and neuralgia pain; treat malnutrition and weight loss.',
    UsesMalayalam: 'നാഡി ശമനം; സന്ധിവാത, നാഡീ വേദന ആശ്വാസം; പോഷകക്കുറവ്, ഭാരക്കുറവ് ചികിത്സ.',
    PageReference: '11v-13',
    SourcePage: 193,
  },
  {
    id: 5,
    category: 'herb',
    ArabicName: 'صبر',
    EnglishName: 'Aloe Vera',
    MalayalamName: 'കറ്റാർവാഴ',
    ScientificName: 'Aloaceae',
    DescriptionEnglish: 'Appears on pages 15r-20 and 27r-13. An Arabic reference for the juices of all bitter plants, especially aloe vera juice. These juices were used in medicine as purges and tonics, as well as for wound healing.',
    DescriptionMalayalam: 'കൊടും കയ്പ്പേറിയ സസ്യ നീരുകൾ, പ്രത്യേകിച്ചും കറ്റാർ നീര്. ശുദ്ധീകരണ ഔഷധം, ടോണിക്ക്, മുറിവ് ഉണക്കൽ എന്നിവയ്ക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Purges and tonics; wound healing.',
    UsesMalayalam: 'ശുദ്ധീകരണ ഔഷധം; ടോണിക്ക്; മുറിവ് ഉണക്കൽ.',
    PageReference: '15r-20, 27r-13',
    SourcePage: 193,
  },
  {
    id: 6,
    category: 'seed',
    ArabicName: 'لوز',
    EnglishName: 'Almond',
    MalayalamName: 'ബദാം',
    ScientificName: 'Prunus dulcis',
    DescriptionEnglish: 'Appears on page 24r-4. Native to West and Central Asia, common in Palestine and Syria. One of the earliest recognized benefits was preventing intoxication. Used for kidney and bladder disorders, heartburn relief, skin cleansing, and as a component in medicinal ointments.',
    DescriptionMalayalam: 'പശ്ചിമ, മധ്യ ഏഷ്യ സ്വദേശി. ലഹരി തടയൽ, വൃക്ക, മൂത്രാശയ പ്രശ്നങ്ങൾ, നെഞ്ചെരിച്ചിൽ ശമനം, ചർമ്മ ശുദ്ധീകരണം എന്നിവയ്ക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Prevent intoxication; kidney and bladder disorders; heartburn relief; skin cleansing; medicinal ointment component; nutritional regimen with sesame, honey, and sugar.',
    UsesMalayalam: 'ലഹരി നിവാരണം; വൃക്ക, മൂത്രാശയ ചികിത്സ; നെഞ്ചെരിച്ചിൽ ശമനം; ചർമ്മ ശുദ്ധീകരണം; ഔഷധ മേൽ‌പ്പൂശൽ.',
    PageReference: '24r-4',
    SourcePage: 194,
  },
  {
    id: 7,
    category: 'flower',
    ArabicName: 'شقايق النعمان',
    EnglishName: 'Anemone',
    MalayalamName: 'അനിമോൺ',
    ScientificName: 'Anemone nemorosa',
    DescriptionEnglish: 'Appears on page 13v, lines 13 and 14. Applied externally for headaches, tertian agues and rheumatic gout. A decoction was highly recommended for the cure of leprosy.',
    DescriptionMalayalam: 'ബാഹ്യ പ്രയോഗം: തലവേദന, ത്രിദിന ജ്വരം, സന്ധിവാതം. കഷായം: കുഷ്ഠരോഗ ചികിത്സ.',
    UsesEnglish: 'Headaches; tertian agues; rheumatic gout (external); decoction for leprosy.',
    UsesMalayalam: 'തലവേദന; ത്രിദിന ജ്വരം; സന്ധിവാതം (ബാഹ്യ); കുഷ്ഠരോഗ കഷായം.',
    PageReference: '13v',
    SourcePage: 194,
  },
  {
    id: 8,
    category: 'herb',
    ArabicName: 'درونج',
    EnglishName: 'Arnica',
    MalayalamName: 'അർണിക്ക',
    ScientificName: 'Arnica montana',
    DescriptionEnglish: 'Appears on pages 10v-1 and 23r-1. Used for pain relief and against bruising.',
    DescriptionMalayalam: 'വേദന ശമനത്തിനും ചതവ് ഭേദമാക്കുന്നതിനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Pain relief; against bruising.',
    UsesMalayalam: 'വേദന ശമനം; ചതവ് ഭേദം.',
    PageReference: '10v-1, 23r-1',
    SourcePage: 194,
  },
  {
    id: 9,
    category: 'resin',
    ArabicName: 'حلتيت / عروق الانجرن',
    EnglishName: 'Asafetida',
    MalayalamName: 'കായം',
    ScientificName: 'Ferula asafoetida',
    DescriptionEnglish: 'Appears on pages 5v, 18r, 21r, and 6v. Has certain medicinal uses; most commonly used as a digestive aid. Reputed to lessen flatulence. Helpful in asthma and bronchitis, and employed against hysteria and nervous afflictions.',
    DescriptionMalayalam: 'ദഹന സഹായി ആയി ഏറ്റവും കൂടുതൽ ഉപയോഗിക്കുന്ന ഔഷധം. വായുക്കുഴപ്പം കുറയ്ക്കുന്നു. ആസ്ത്മ, ബ്രോങ്കൈറ്റിസ്, ഹിസ്റ്റീരിയ, നാഡീ ദൗർബല്യം എന്നിവയ്ക്ക് ഉപകാരപ്രദം.',
    UsesEnglish: 'Digestive aid; reduce flatulence; asthma and bronchitis; hysteria and nervous afflictions.',
    UsesMalayalam: 'ദഹന സഹായം; വായുക്കുഴപ്പം കുറക്കൽ; ആസ്ത്മ, ബ്രോങ്കൈറ്റിസ്; ഹിസ്റ്റീരിയ, നാഡി ദൗർബല്യം.',
    PageReference: '5v, 18r, 21r, 6v',
    SourcePage: 194,
  },
  {
    id: 10,
    category: 'herb',
    ArabicName: 'الغار',
    EnglishName: 'Bay Leaves',
    MalayalamName: 'ബേ ഇല',
    ScientificName: 'Lauris nobilis',
    DescriptionEnglish: 'Found on page 10r-7. Used mainly to treat upper digestive tract disorders and to ease arthritic aches and pains.',
    DescriptionMalayalam: 'ഉപരി ദഹനേന്ദ്രിയ ക്രമക്കേടുകൾ ചികിത്സിക്കാനും സന്ധിവേദന ഒഴിവാക്കാനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Upper digestive tract disorders; ease arthritic aches and pains.',
    UsesMalayalam: 'ദഹന ക്രമക്കേട് ചികിത്സ; സന്ധിവേദന ശമനം.',
    PageReference: '10r-7',
    SourcePage: 194,
  },
  {
    id: 11,
    category: 'fruit',
    ArabicName: 'الكاد',
    EnglishName: 'Betal Palm Nut',
    MalayalamName: 'അടക്ക',
    ScientificName: 'Areca catechu',
    DescriptionEnglish: 'Found on page 25r-15. Used medicinally to remove tapeworms and other digestive parasites.',
    DescriptionMalayalam: 'ടേപ്പ്‌വേം, മറ്റ് ദഹന പരാദ ജീവികൾ നീക്കം ചെയ്യാൻ ഔഷധമായി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Remove tapeworms and other digestive parasites.',
    UsesMalayalam: 'ടേപ്പ്‌വേം, ദഹന പരാദ നിർമ്മാർജ്ജനം.',
    PageReference: '25r-15',
    SourcePage: 194,
  },
  {
    id: 12,
    category: 'other',
    ArabicName: 'مرارة',
    EnglishName: 'Bile',
    MalayalamName: 'പിത്തരസം',
    ScientificName: '',
    DescriptionEnglish: 'Various animal biles (snake, crow, wolf, cow, ram, viper, goat, crane) appear throughout the manuscript. Bile was an important part of ancient medicine in both Greece and Rome, considered one of the four humors. Used medicinally for thousands of years across many traditions including Chinese and Islamic medicine.',
    DescriptionMalayalam: 'പല മൃഗങ്ങളുടെ (സർപ്പം, കാക്ക, ചെന്നായ, പശു, ആട്, ക്രൗഞ്ചം) പിത്തരസം ഗ്രന്ഥത്തിൽ കാണുന്നു. ഗ്രീക്ക്, റോം ചികിത്സയിൽ നാലു ദ്രവ്യങ്ങളിൽ ഒന്ന്.',
    UsesEnglish: 'Cut thirst; bind the bowels; treat rheumatic pain, high fever, convulsions, hemorrhoids, bleeding gums, whooping cough, skin infections.',
    UsesMalayalam: 'ദാഹ ശമനം; കുടൽ ബന്ധനം; സന്ധിവേദന, പനി, ബേധം, മൂലം, ചർമ്മ അണുബാധ ചികിത്സ.',
    PageReference: '3r-20, 4r-12, 5v-5, 6r-10, 11r-14, 16v-6',
    SourcePage: 195,
  },
  {
    id: 13,
    category: 'seed',
    ArabicName: 'شونيز',
    EnglishName: 'Black Cumin / Black Onion Seeds',
    MalayalamName: 'കരിഞ്ജീരകം',
    ScientificName: 'Nigella sativa',
    DescriptionEnglish: 'Appears on pages 8v-4 and 19v-14. Black cumin or black onion seed. Traditionally used to stimulate the body\'s energy, aid recovery from fatigue and dispiritedness. Used for respiratory health, stomach and intestinal health, kidney and liver function, circulatory and immune system support, and general overall well-being.',
    DescriptionMalayalam: 'ഊർജ്ജ ഉത്തേജനം, ക്ഷീണ ദൂരീകരണം, ശ്വസന ആരോഗ്യം, ദഹനശക്തി, വൃക്ക, കരൾ പ്രവർത്തനം, രക്ത, പ്രതിരോധ ശക്തി വർദ്ധനവ്.',
    UsesEnglish: 'Stimulate energy; recovery from fatigue; respiratory health; stomach and intestinal health; kidney and liver function; circulatory and immune support; general well-being.',
    UsesMalayalam: 'ഊർജ്ജ ഉത്തേജനം; ക്ഷീണ ദൂരീകരണം; ശ്വസനാരോഗ്യം; ദഹനശക്തി; വൃക്ക, കരൾ ആരോഗ്യം; രക്ത, പ്രതിരോധ ശക്തി.',
    PageReference: '8v-4, 19v-14',
    SourcePage: '195-196',
  },
  {
    id: 14,
    category: 'herb',
    ArabicName: 'حزبق',
    EnglishName: 'Black Hellebore',
    MalayalamName: 'കറുത്ത ഹെല്ലിബോർ',
    ScientificName: 'Helleborus officinalis',
    DescriptionEnglish: 'Appears on pages 10v-2 and 19r-18. Used as a purgative in mania and proved of value in nervous disorders and hysteria. Administered in the form of a tincture with great care.',
    DescriptionMalayalam: 'ഭ്രാന്ത്, നാഡി ക്രമക്കേട്, ഹിസ്റ്റീരിയ ചികിത്സയ്ക്ക് ഉപയോഗിക്കുന്ന ശക്തമായ ഔഷധം. ടിൻചർ രൂപത്തിൽ ജാഗ്രതയോടെ നൽകണം.',
    UsesEnglish: 'Purgative in mania; nervous disorders; hysteria. Administered as a tincture with care.',
    UsesMalayalam: 'ഭ്രാന്ത് ശുദ്ധീകരണം; നാഡി ക്രമക്കേട്; ഹിസ്റ്റീരിയ.',
    PageReference: '10v-2, 19r-18',
    SourcePage: 196,
  },
  {
    id: 15,
    category: 'other',
    ArabicName: 'زبد الجمل',
    EnglishName: 'Camel Milk Butter',
    MalayalamName: 'ഒട്ടക പാൽ വെണ്ണ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on pages 5r-7 and 7v-8. Because there was very little fat in camel milk, it was hard to make and was not eaten, but used as a base for medicines.',
    DescriptionMalayalam: 'ഒട്ടകപ്പാലിൽ കൊഴുപ്പ് വളരെ കുറവായതിനാൽ ഉണ്ടാക്കാൻ പ്രയാസം. ഭക്ഷണത്തിനല്ല, ഔഷധ അടിത്തറ ആയി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Used as a base for medicines.',
    UsesMalayalam: 'ഔഷധ അടിത്തറ.',
    PageReference: '5r-7, 7v-8',
    SourcePage: 196,
  },
  {
    id: 16,
    category: 'seed',
    ArabicName: 'حبة كافر',
    EnglishName: 'Camphor Seed',
    MalayalamName: 'കർപ്പൂര വിത്ത്',
    ScientificName: 'Cinnamomum Camphora / Laurus Camphora',
    DescriptionEnglish: 'Appears on page 23r-2. The manuscript refers specifically to camphor seed, which grows in China and Japan. The Arabs introduced its use in medicine to the West. Used in traditional medicine for poor circulation, painful joints, and breathing and sinus problems.',
    DescriptionMalayalam: 'ചൈനയിലും ജപ്പാനിലും വളരുന്ന കർപ്പൂര വിത്ത്. അറബികൾ ഇതിന്റെ ഉപയോഗം പടിഞ്ഞാറ് പരിചയപ്പെടുത്തി. രക്ത ചംക്രമണം, സന്ധി വേദന, ശ്വസന, സൈനസ് പ്രശ്നങ്ങൾക്ക് ഉപകരിക്കുന്നു.',
    UsesEnglish: 'Poor circulation; painful joints; breathing and sinus problems.',
    UsesMalayalam: 'രക്ത ചംക്രമണ ദൗർബല്യം; സന്ധി വേദന; ശ്വസന, സൈനസ് ചികിത്സ.',
    PageReference: '23r-2',
    SourcePage: 196,
  },
  {
    id: 17,
    category: 'herb',
    ArabicName: 'نبات القصب',
    EnglishName: 'Cane Plant',
    MalayalamName: 'കരിമ്പ് ചെടി',
    ScientificName: 'Saccharum officinarum',
    DescriptionEnglish: 'Found on pages 25r-9 and 6v-18, 34. The cane plant. Used as a sweetener for many bitter remedies.',
    DescriptionMalayalam: 'കയ്പ്പേറിയ ഔഷധങ്ങൾ മധുരമാക്കാൻ ഉപയോഗിക്കുന്ന കരിമ്പ് ചെടി.',
    UsesEnglish: 'Sweetener for bitter remedies.',
    UsesMalayalam: 'കയ്പ്പ് ഔഷധ മധുരീകരണം.',
    PageReference: '25r-9, 6v-18',
    SourcePage: 196,
  },
  {
    id: 18,
    category: 'root',
    ArabicName: 'عروق القصب',
    EnglishName: 'Cane Root',
    MalayalamName: 'കരിമ്പ് വേര്',
    ScientificName: 'Calamus aromaticus',
    DescriptionEnglish: 'Appears on pages 6v-18, 7v-7, 7v-8, and 26v-18. Most likely refers to the Sweet Flag (Calamus aromaticus of Dioscorides). Used to support the healing of wounds, scars and acne.',
    DescriptionMalayalam: 'ഡയോസ്കോറിഡീസിന്റെ കലാമസ് അരോമാറ്റിക്കസ് (Sweet Flag) ആകാൻ സാധ്യത. മുറിവ്, പാടുകൾ, മുഖക്കുരു ഭേദപ്പെടുത്തൽ.',
    UsesEnglish: 'Healing of wounds, scars and acne.',
    UsesMalayalam: 'മുറിവ്, പാടുകൾ, മുഖക്കുരു ഭേദം.',
    PageReference: '6v-18, 7v-7, 7v-8, 26v-18',
    SourcePage: 196,
  },
  {
    id: 19,
    category: 'oil',
    ArabicName: 'جندبادستر',
    EnglishName: 'Castor Oil',
    MalayalamName: 'ആവണക്കെണ്ണ',
    ScientificName: 'Ricinus Communis',
    DescriptionEnglish: 'Appears on pages 8r-7, 10v-1, 10v-2, and 21r-21. Used as a laxative, for intestinal inflammation and worms. In homeopathy for digestive complaints. In Asian medicine for joint pain, dry stool, indigestion, facial paralysis, boils and ulcers.',
    DescriptionMalayalam: 'വിരേചകം, കുടൽ ജ്വലനം, കൃമി നാശം. ദഹന പ്രശ്നങ്ങൾ, സന്ധി വേദന, മലബന്ധം, ദഹനക്കേട്, മുഖ തളർവാതം, ചെളിക്കുരു, വ്രണം ചികിത്സ.',
    UsesEnglish: 'Laxative; intestinal inflammation; worms; digestive complaints; joint pain; dry stool; indigestion; facial paralysis; boils and ulcers.',
    UsesMalayalam: 'വിരേചനം; കുടൽ ജ്വലനം; കൃമി; ദഹന പ്രശ്നം; സന്ധി വേദന; മലബന്ധം; ദഹനക്കേട്; മുഖ തളർവാതം.',
    PageReference: '8r-7, 10v-1, 10v-2, 21r-21',
    SourcePage: 197,
  },
  {
    id: 20,
    category: 'herb',
    ArabicName: 'الهندبا / اصفر سلم',
    EnglishName: 'Chicory',
    MalayalamName: 'ചിക്കറി',
    ScientificName: 'Cichorium intybus',
    DescriptionEnglish: 'Appears on pages 17r-16 and 17r-14. Used since the 1st century C.E. The Egyptians used it to purify the blood and liver. Taken internally for spleen problems, gallstones, jaundice, rheumatism, and loss of appetite. Also used as a laxative and to increase the flow of bile.',
    DescriptionMalayalam: 'ക്രി.ശ. ഒന്നാം നൂറ്റാണ്ട് മുതൽ ഉപയോഗത്തിൽ. രക്തം, കരൾ ശുദ്ധീകരണം. പ്ലീഹ, ഗാൾസ്റ്റോൺ, മഞ്ഞപ്പിത്തം, സന്ധിവാതം, വിശപ്പില്ലായ്മ ചികിത്സ.',
    UsesEnglish: 'Blood and liver purification; spleen problems; gallstones; jaundice; rheumatism; loss of appetite; laxative; increase bile flow.',
    UsesMalayalam: 'രക്ത, കരൾ ശുദ്ധീകരണം; പ്ലീഹ, ഗാൾസ്റ്റോൺ; മഞ്ഞപ്പിത്തം; സന്ധിവാതം; വിശപ്പില്ലായ്മ; വിരേചനം.',
    PageReference: '17r-16, 17r-14',
    SourcePage: 197,
  },
  {
    id: 21,
    category: 'root',
    ArabicName: 'الروند الصينى',
    EnglishName: 'Chinese Rhubarb',
    MalayalamName: 'ചൈനീസ് റൂബാർബ്',
    ScientificName: 'Rheum rhaponticum',
    DescriptionEnglish: 'Appears on page 3r-1. From northwest China and Tibet. A favorite remedy of early Persian and Arabian physicians for over 2000 years. Used for constipation and diarrhea depending on dosage. Also for boils, burns, and as a mouthwash for canker sores. Note: leaves and roots are toxic due to high oxalic acid content. Also appears as Long Rhubarb (الروند الطويل) on pages 4r-16 and 16r-6.',
    DescriptionMalayalam: 'വടക്കുപടിഞ്ഞാറൻ ചൈന, ടിബറ്റ് സ്വദേശി. 2000 വർഷത്തിലധികം ഉപയോഗം. ഡോസ് അനുസരിച്ച് മലബന്ധം / വയറിളക്കം ചികിത്സ. ചെളിക്കുരു, പൊള്ളൽ, വായ്‌പ്പുണ്ണ്. ഇലകളും വേരും വിഷകരം.',
    UsesEnglish: 'Constipation and diarrhea (dose-dependent); boils; burns; mouthwash for canker sores.',
    UsesMalayalam: 'മലബന്ധം/വയറിളക്കം; ചെളിക്കുരു; പൊള്ളൽ; വായ്‌പ്പുണ്ണ് ഗ്ലർഗ്ഗൾ.',
    PageReference: '3r-1, 4r-16, 16r-6',
    SourcePage: '197-198',
  },
  {
    id: 22,
    category: 'herb',
    ArabicName: 'كزبورة اليابسة',
    EnglishName: 'Cilantro (Dried)',
    MalayalamName: 'ഉണക്ക മല്ലി',
    ScientificName: 'Coriandrum sativum',
    DescriptionEnglish: 'Appears on page 10v-18. Used for the relief of anxiety and insomnia, also as a diuretic in combination with cumin seed.',
    DescriptionMalayalam: 'ഉത്കണ്ഠ, ഉറക്കക്കുറവ് ശമനം. ജീരകത്തോടൊപ്പം മൂത്ര ഉത്തേജനത്തിനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Relief of anxiety and insomnia; diuretic (combined with cumin seed).',
    UsesMalayalam: 'ഉത്കണ്ഠ, ഉറക്കക്കുറവ്; മൂത്ര ഉത്തേജനം (ജീരകത്തോടൊപ്പം).',
    PageReference: '10v-18',
    SourcePage: 198,
  },
  {
    id: 23,
    category: 'spice',
    ArabicName: 'سليحة',
    EnglishName: 'Cinnamon',
    MalayalamName: 'ഇലവംഗം',
    ScientificName: 'Cinnamomum Cassia',
    DescriptionEnglish: 'Appears on page 26v-16. Used to treat diarrhea and kidney disorders, as well as to warm the body, promote circulation, and heal colds.',
    DescriptionMalayalam: 'വയറിളക്കം, വൃക്ക ക്രമക്കേട് ചികിത്സ. ശരീരം ചൂടാക്കൽ, രക്ത ചംക്രമണം, ജലദോഷം ഭേദപ്പെടുത്തൽ.',
    UsesEnglish: 'Diarrhea; kidney disorders; warm the body; promote circulation; heal colds.',
    UsesMalayalam: 'വയറിളക്കം; വൃക്ക ചികിത്സ; ശരീര ചൂട്; രക്ത ചംക്രമണം; ജലദോഷം.',
    PageReference: '26v-16',
    SourcePage: 198,
  },
  {
    id: 24,
    category: 'other',
    ArabicName: 'دهن كادير',
    EnglishName: 'Cloudy Salve',
    MalayalamName: 'മേഘ ലേഹ്യം',
    ScientificName: '',
    DescriptionEnglish: 'Found on pages 14v-6, 28-4, and 29v-1. Called cloudy (rose) salve or grease. Used as a base for other ingredients.',
    DescriptionMalayalam: 'മേഘ (റോസ്) ലേഹ്യം അല്ലെങ്കിൽ കൊഴുപ്പ് എന്ന് വിളിക്കുന്നു. മറ്റ് ഔഷധ ഘടകങ്ങളുടെ അടിത്തറ.',
    UsesEnglish: 'Base for other ingredients.',
    UsesMalayalam: 'ഔഷധ ഘടക അടിത്തറ.',
    PageReference: '14v-6, 28-4, 29v-1',
    SourcePage: 198,
  },
  {
    id: 25,
    category: 'spice',
    ArabicName: 'قرنفل',
    EnglishName: 'Cloves',
    MalayalamName: 'ഗ്രാമ്പൂ',
    ScientificName: 'Caryophyllus aromaticus',
    DescriptionEnglish: 'Appears on page 8v-7. Long history of use in natural medicine East and West. Used to treat nausea, indigestion, vomiting, and diarrhea. Also for infertility, war wounds, and toothaches.',
    DescriptionMalayalam: 'കിഴക്ക്, പടിഞ്ഞാറൻ പ്രകൃതി ചികിത്സയിൽ നദീം. ഓക്കാനം, ദഹനക്കേട്, ഛർദ്ദി, വയറിളക്കം. വന്ധ്യത, യുദ്ധ മുറിവ്, പല്ലുവേദന ചികിത്സ.',
    UsesEnglish: 'Nausea; indigestion; vomiting; diarrhea; infertility; war wounds; toothaches.',
    UsesMalayalam: 'ഓക്കാനം; ദഹനക്കേട്; ഛർദ്ദി; വയറിളക്കം; വന്ധ്യത; മുറിവ്; പല്ലുവേദന.',
    PageReference: '8v-7',
    SourcePage: 198,
  },
  {
    id: 26,
    category: 'seed',
    ArabicName: 'شونس',
    EnglishName: 'Corncockle',
    MalayalamName: 'കർൺകോക്കിൾ',
    ScientificName: 'Nigella sativa',
    DescriptionEnglish: 'Appears on page 19v-14. More commonly known as black cumin. Used for respiratory health, stomach and intestinal health, kidney and liver function, circulatory and immune support, and general well-being. Also used to treat abscesses and tumors of the abdomen, eyes, and liver, and highly efficacious against intestinal parasites.',
    DescriptionMalayalam: 'കരിഞ്ജീരകം എന്ന് കൂടുതൽ അറിയപ്പെടുന്നു. ശ്വസനം, ദഹനം, വൃക്ക, കരൾ, രക്ത, പ്രതിരോധ ആരോഗ്യം. വയർ, കണ്ണ്, കരൾ കഴലകൾ, കുടൽ പരാദ ചികിത്സ.',
    UsesEnglish: 'Respiratory, digestive, kidney, liver, circulatory, immune health; abscesses and tumors; intestinal parasites.',
    UsesMalayalam: 'ശ്വസന, ദഹന, വൃക്ക, കരൾ ആരോഗ്യം; കഴലകൾ; കുടൽ പരാദ നിർമ്മാർജ്ജനം.',
    PageReference: '19v-14',
    SourcePage: 198,
  },
  {
    id: 27,
    category: 'root',
    ArabicName: 'قسط',
    EnglishName: 'Costus Root',
    MalayalamName: 'കോഷ്ഠം',
    ScientificName: 'Saussurea iappa',
    DescriptionEnglish: 'Appears on page 13r-16. Used in the treatment of bronchial asthma, cholera, cough, dyspepsia, edema, gas, hiccup, jaundice, leprosy, phlegm, rheumatism, and skin diseases. Applied externally as an ointment for wounds, ulcerations, skin diseases, and tumors. Can also be used as a narcotic when smoked.',
    DescriptionMalayalam: 'ബ്രോങ്കിയൽ ആസ്ത്മ, കോളറ, ചുമ, ദഹനക്കേട്, നീർക്കെട്ട്, ഗ്യാസ്, ഓക്കൾ, മഞ്ഞപ്പിത്തം, കുഷ്ഠം, ശ്ലേഷ്മം, സന്ധിവാതം, ചർമ്മ രോഗം ചികിത്സ.',
    UsesEnglish: 'Bronchial asthma; cholera; cough; dyspepsia; edema; jaundice; leprosy; rheumatism; skin diseases; external ointment for wounds and tumors; narcotic when smoked.',
    UsesMalayalam: 'ആസ്ത്മ; കോളറ; ചുമ; ദഹനക്കേട്; നീർക്കെട്ട്; മഞ്ഞപ്പിത്തം; കുഷ്ഠം; സന്ധിവാതം; ചർമ്മ ചികിത്സ.',
    PageReference: '13r-16',
    SourcePage: 199,
  },
  {
    id: 28,
    category: 'other',
    ArabicName: 'ماء دينادى',
    EnglishName: 'Croton',
    MalayalamName: 'ക്രോട്ടൺ',
    ScientificName: 'Croton tiglium',
    DescriptionEnglish: 'Appears on page 25r-15. Used as a purgative.',
    DescriptionMalayalam: 'ശുദ്ധീകരണ ഔഷധം ആയി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Purgative.',
    UsesMalayalam: 'ശുദ്ധീകരണം.',
    PageReference: '25r-15',
    SourcePage: 199,
  },
  {
    id: 29,
    category: 'resin',
    ArabicName: 'شبان',
    EnglishName: "Dragon's Blood",
    MalayalamName: 'ഡ്രാഗൺസ് ബ്ലഡ്',
    ScientificName: 'Dracaena Cinnabari',
    DescriptionEnglish: "Appears on page 16r-6. The dragon's blood tree stretched from the Canaries through the Mediterranean to Southern Russia. Cinnabar extracted from leaves and barks was used as a pigment in paint and in treating burns, dysentery, stomach problems, and tightening loose teeth.",
    DescriptionMalayalam: 'കനറി ദ്വീപ് മുതൽ ദക്ഷിണ റഷ്യ വരെ വ്യാപിച്ചിരുന്ന വൃക്ഷം. ഇലകളിൽ നിന്നുള്ള ചായം, പൊള്ളൽ, ഒഴിച്ചിൽ, ഉദരരോഗം, പല്ല് ബലഹീനത ചികിത്സ.',
    UsesEnglish: 'Pigment in paint; burns; dysentery; stomach problems; tightening loose teeth.',
    UsesMalayalam: 'ചായം; പൊള്ളൽ; ഒഴിച്ചിൽ; ഉദര ചികിത്സ; പല്ല് ബലഹീനത.',
    PageReference: '16r-6',
    SourcePage: 199,
  },
  {
    id: 30,
    category: 'herb',
    ArabicName: 'بقل',
    EnglishName: 'Endive',
    MalayalamName: 'എൻഡൈവ്',
    ScientificName: 'Cichorium endivia',
    DescriptionEnglish: 'Appears on page 23v-13. First mentioned by Arabic physicians in the 10th and 11th centuries. A kind of wild dandelion known as Taraxcacon. Used as a general system tonic, especially for the urinary organs, and mainly to treat kidney and liver disorders.',
    DescriptionMalayalam: '10-11 നൂറ്റാണ്ടിലെ അറബി വൈദ്യന്മാർ ആദ്യം പരാമർശിച്ചു. ടരാക്സകോൺ എന്ന കാട്ടു ഡാൻഡെലിയോൺ. മൂത്രാശയ അവയവ ടോണിക്ക്; വൃക്ക, കരൾ ക്രമക്കേട്.',
    UsesEnglish: 'General system tonic; urinary organ tonic; kidney and liver disorders.',
    UsesMalayalam: 'പൊതു ടോണിക്ക്; മൂത്രാശയ ടോണിക്ക്; വൃക്ക, കരൾ ചികിത്സ.',
    PageReference: '23v-13',
    SourcePage: 199,
  },
  {
    id: 31,
    category: 'herb',
    ArabicName: 'فربيون',
    EnglishName: 'Euphorbia',
    MalayalamName: 'യൂഫോർബിയ',
    ScientificName: 'Euphorbia spp.',
    DescriptionEnglish: 'Appears on pages 4r-16, 5v-5, 8r-6, 29r-21, 20v-4, and 5v-15. Has more than two thousand species. Named after Greek surgeon Euphorbus who used the milky latex in potions. Main use was as a purgative.',
    DescriptionMalayalam: 'രണ്ടായിരത്തിലധികം ഇനങ്ങൾ. ഗ്രീക്ക് ശസ്ത്രക്രിയാ വിദഗ്ധൻ യൂഫോർബസിന്റെ പേരിൽ. പ്രധാന ഉപയോഗം ശുദ്ധീകരണം.',
    UsesEnglish: 'Purgative.',
    UsesMalayalam: 'ശുദ്ധീകരണ ഔഷധം.',
    PageReference: '4r-16, 5v-5, 8r-6, 29r-21, 20v-4, 5v-15',
    SourcePage: 199,
  },
  {
    id: 32,
    category: 'other',
    ArabicName: 'بعر التيس',
    EnglishName: 'Goat Excrement',
    MalayalamName: 'ആട്ടിൻ കാഷ്ഠം',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 5v, line 3. Mixed with goat hooves, euphorbia, saffron, and asafetida in compound remedies.',
    DescriptionMalayalam: 'ആട്ടിൻ കുളമ്പ്, യൂഫോർബിയ, കുങ്കുമം, കായം ചേർത്ത് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Component in compound remedies with goat hooves, euphorbia, saffron, and asafetida.',
    UsesMalayalam: 'സംയുക്ത ഔഷധ ഘടകം.',
    PageReference: '5v',
    SourcePage: 200,
  },
  {
    id: 33,
    category: 'other',
    ArabicName: 'شحم حية سودا',
    EnglishName: 'Fat — Black Snake',
    MalayalamName: 'കറുത്ത പാമ്പിന്റെ കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 16v-20. The fat of a black snake was used as a remedy for hemorrhoids.',
    DescriptionMalayalam: 'കറുത്ത പാമ്പിന്റെ കൊഴുപ്പ് മൂലരോഗ ചികിത്സ.',
    UsesEnglish: 'Remedy for hemorrhoids.',
    UsesMalayalam: 'മൂലരോഗ ചികിത്സ.',
    PageReference: '16v-20',
    SourcePage: 200,
  },
  {
    id: 34,
    category: 'other',
    ArabicName: 'شحم سنور',
    EnglishName: 'Fat — Cat',
    MalayalamName: 'പൂച്ചക്കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears in the manuscript on page 13r. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '13r',
    SourcePage: 200,
  },
  {
    id: 35,
    category: 'other',
    ArabicName: 'شحم حمار وحش',
    EnglishName: 'Fat — Wild Donkey',
    MalayalamName: 'കാട്ടു കഴുതക്കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 29r, lines 14 and 15. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '29r',
    SourcePage: 200,
  },
  {
    id: 36,
    category: 'other',
    ArabicName: 'سمن البقر',
    EnglishName: 'Fat — Cow Tallow',
    MalayalamName: 'പശുവിൻ കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Found on pages 10r-7, 18r-16, and 22r-10. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '10r-7, 18r-16, 22r-10',
    SourcePage: 200,
  },
  {
    id: 37,
    category: 'other',
    ArabicName: 'سمن الغنم',
    EnglishName: 'Fat — Sheep Tallow',
    MalayalamName: 'ആടിൻ കൊഴുപ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Found on page 25r-10. Animal fat used mainly for emollient purposes.',
    DescriptionMalayalam: 'പ്രധാനമായും മൃദൂകരണ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Emollient purposes.',
    UsesMalayalam: 'മൃദൂകരണം.',
    PageReference: '25r-10',
    SourcePage: 200,
  },
  {
    id: 38,
    category: 'resin',
    ArabicName: 'لبان / الكرنزون',
    EnglishName: 'Frankincense',
    MalayalamName: 'കുന്തിരിക്കം',
    ScientificName: 'Boswellia carterii',
    DescriptionEnglish: 'Appears on pages 15v and 16r-6. A natural antiseptic resin. Used in treatment of womb disorders (hot compresses soaked in frankincense tea applied to belly) and chronic respiratory illnesses (patient inhales fumes from burning resin).',
    DescriptionMalayalam: 'പ്രകൃതിദത്ത അണുനാശിനി. ഗർഭപാത്ര ക്രമക്കേട് (ചൂട് കമ്പ്രസ്), ദീർഘകാല ശ്വസന രോഗം (ദഹന ആവി ശ്വസനം) ചികിത്സ.',
    UsesEnglish: 'Natural antiseptic; womb disorders (hot compress); chronic respiratory illness (inhaling burning fumes).',
    UsesMalayalam: 'അണുനാശിനി; ഗർഭാശയ ചികിത്സ; ശ്വസന രോഗ ചികിത്സ.',
    PageReference: '15v, 16r-6',
    SourcePage: 200,
  },
  {
    id: 39,
    category: 'other',
    ArabicName: 'دماغ الضفدع',
    EnglishName: 'Frog Brain',
    MalayalamName: 'തവളയുടെ തലച്ചോർ',
    ScientificName: '',
    DescriptionEnglish: 'Found on page 25r-10. Used to treat hemorrhoids, wounds, bleeding and rheumatism.',
    DescriptionMalayalam: 'മൂലം, മുറിവ്, രക്തസ്രാവം, സന്ധിവാതം ചികിത്സ.',
    UsesEnglish: 'Hemorrhoids; wounds; bleeding; rheumatism.',
    UsesMalayalam: 'മൂലം; മുറിവ്; രക്തസ്രാവം; സന്ധിവാതം.',
    PageReference: '25r-10',
    SourcePage: 200,
  },
  {
    id: 40,
    category: 'resin',
    ArabicName: 'غلبله / عروق القنه',
    EnglishName: 'Galbanum',
    MalayalamName: 'ഗൽബനം',
    ScientificName: 'Ferula gummosa',
    DescriptionEnglish: 'Appears on pages 7v-7 and 17v-8. Used in healing remedies and in liturgical perfumes in Jewish prayers. Valued for its sedative and analgesic properties.',
    DescriptionMalayalam: 'ഉദ്ഗ്രഥനം, ജൂത പ്രാർഥന ധൂപ ദ്രവ്യം. ഉറക്ക ഔഷധ, വേദന ശമന ഗുണങ്ങൾ.',
    UsesEnglish: 'Healing remedies; liturgical perfume; sedative; analgesic.',
    UsesMalayalam: 'ഉദ്ഗ്രഥന ഔഷധം; ആരാധനാ ധൂപം; ഉറക്ക ഔഷധം; വേദന ശമനം.',
    PageReference: '7v-7, 17v-8',
    SourcePage: 200,
  },
  {
    id: 41,
    category: 'root',
    ArabicName: 'زنجبيل',
    EnglishName: 'Ginger',
    MalayalamName: 'ഇഞ്ചി',
    ScientificName: 'Zingiber officinale',
    DescriptionEnglish: 'Appears on page 23v-12. Name derives from Sanskrit Shringavera (horn body). Used in traditional medicine for more than 5,000 years. Used to treat stomachache, indigestion, motion sickness, fever, malaria, rheumatoid arthritis, and migraine. Also used to improve circulation and reduce fat deposits in the arteries.',
    DescriptionMalayalam: 'സംസ്കൃത ശ്രിംഗാവേര (കൊമ്പ് ശരീരം) എന്ന വാക്കിൽ നിന്ന്. 5000 വർഷം ഔഷധ ഉപയോഗം. ഉദര വേദന, ദഹനക്കേട്, ചലന രോഗം, ജ്വരം, മലേറിയ, സന്ധിവാതം, മൈഗ്രൈൻ. രക്ത ചംക്രമണ മെച്ചം, ധമനി കൊഴുപ്പ് കുറക്കൽ.',
    UsesEnglish: 'Stomachache; indigestion; motion sickness; fever; malaria; rheumatoid arthritis; migraine; improve circulation; reduce arterial fat deposits.',
    UsesMalayalam: 'ഉദര വേദന; ദഹനക്കേട്; ചലന രോഗം; ജ്വരം; മലേറിയ; സന്ധിവാതം; മൈഗ്രൈൻ; രക്ത ചംക്രമണം.',
    PageReference: '23v-12',
    SourcePage: 200,
  },
  {
    id: 42,
    category: 'other',
    ArabicName: 'ظفر التيس',
    EnglishName: 'Goat Hooves',
    MalayalamName: 'ആടിൻ കുളമ്പ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 5v, line 2. Hooves and excrement of male goats were used in the cure of illnesses caused by evil jinni residing in ruins and in the deserts.',
    DescriptionMalayalam: 'ആണ്‍ ആടിന്റെ കുളമ്പും കാഷ്ഠവും, ഭൂതോച്ചാടനം, ജിന്ന് ബാധ ചികിത്സ.',
    UsesEnglish: 'Cure of illnesses caused by evil jinni (combined with goat excrement).',
    UsesMalayalam: 'ജിന്ന് ബാധ ചികിത്സ.',
    PageReference: '5v',
    SourcePage: 200,
  },
  {
    id: 43,
    category: 'other',
    ArabicName: 'عصير العنب',
    EnglishName: 'Grape Wine',
    MalayalamName: 'മുന്തിരി വീഞ്ഞ്',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 24r-4. An alcoholic drink made from grapes or dry dates. The manuscript admonishes abstinence from it as part of the recommended nutritional treatment.',
    DescriptionMalayalam: 'മുന്തിരിയിൽ നിന്നോ ഉണക്ക ഈത്തപ്പഴത്തിൽ നിന്നോ ഉണ്ടാക്കുന്ന ലഹരി. ഗ്രന്ഥം പോഷകചികിത്സ ഭാഗമായി ഇതിൽ നിന്ന് വിരമിക്കാൻ ഉദ്ബോധിപ്പിക്കുന്നു.',
    UsesEnglish: 'Referenced in nutritional context; manuscript advises abstinence.',
    UsesMalayalam: 'പോഷകചികിത്സ; ഗ്രന്ഥം ഒഴിവാക്കാൻ ഉദ്ബോധിപ്പിക്കുന്നു.',
    PageReference: '24r-4',
    SourcePage: 200,
  },
  {
    id: 44,
    category: 'oil',
    ArabicName: 'زيت انفاق',
    EnglishName: 'Green Olive Oil',
    MalayalamName: 'പച്ച ഒലിവ് എണ്ണ',
    ScientificName: '',
    DescriptionEnglish: 'Appears on page 3v-16. Green olive oil used in cooking. Considered one of the healthier cooking oils.',
    DescriptionMalayalam: 'പാചകത്തിന് ഉപയോഗിക്കുന്ന പച്ച ഒലിവ് എണ്ണ. ആരോഗ്യകരമായ പാചക എണ്ണ.',
    UsesEnglish: 'Cooking oil.',
    UsesMalayalam: 'പാചക എണ്ണ.',
    PageReference: '3v-16',
    SourcePage: 200,
  },
  {
    id: 45,
    category: 'herb',
    ArabicName: 'حناء',
    EnglishName: 'Henna',
    MalayalamName: 'മൈലാഞ്ചി',
    ScientificName: 'Lawsonia inermis',
    DescriptionEnglish: 'Appears on pages 7v-8 and 14v-20. Traditionally used medicinally and cosmetically. Used for treatment of burns, ulcers of the mouth and stomach, and hot swellings. Mixed with butter or oil as a poultice, and as a treatment for scabies, mites and mange.',
    DescriptionMalayalam: 'ഔഷധ, സൗന്ദര്യ ആവശ്യങ്ങൾക്ക് പരമ്പരാഗതമായി ഉപയോഗിക്കുന്നു. പൊള്ളൽ, വായ്, ഉദര വ്രണം, ചൂട് നീർക്കെട്ട്, ചൊറി, ചേർ, കുഷ്ഠ ചർമ്മ രോഗം ചികിത്സ.',
    UsesEnglish: 'Burns; mouth and stomach ulcers; hot swellings; poultice (with butter or oil); scabies; mites; mange.',
    UsesMalayalam: 'പൊള്ളൽ; വായ്, ഉദര വ്രണം; ചൂട് നീർക്കെട്ട്; ചൊറി; ചേർ; ചർമ്മ രോഗം.',
    PageReference: '7v-8, 14v-20',
    SourcePage: 200,
  },
  ...PLANTS_DATA_2,
];