// ═══════════════════════════════════════════════════════════════
// PLANTS & INGREDIENTS DICTIONARY — STANDALONE DATA
// Schema: ArabicName, EnglishName, MalayalamName, ScientificName,
//         DescriptionEnglish, DescriptionMalayalam,
//         UsesEnglish, UsesMalayalam, PageReference, SourcePage
// Completely isolated. Zero imports from any engine or lib file.
// ═══════════════════════════════════════════════════════════════

export const PLANT_CATEGORIES = [
  { id: 'all',    label: 'All',     arabic: 'الكل',     ml: 'എല്ലാം' },
  { id: 'herb',   label: 'Herbs',   arabic: 'الأعشاب',  ml: 'ഔഷധസസ്യം' },
  { id: 'spice',  label: 'Spices',  arabic: 'التوابل',  ml: 'സുഗന്ധദ്രവ്യം' },
  { id: 'resin',  label: 'Resins',  arabic: 'الصمغ',    ml: 'റെസിൻ' },
  { id: 'root',   label: 'Roots',   arabic: 'الجذور',   ml: 'വേര്' },
  { id: 'flower', label: 'Flowers', arabic: 'الأزهار',  ml: 'പൂക്കൾ' },
  { id: 'fruit',  label: 'Fruits',  arabic: 'الفواكه',  ml: 'ഫലം' },
  { id: 'seed',   label: 'Seeds',   arabic: 'البذور',   ml: 'വിത്ത്' },
  { id: 'oil',    label: 'Oils',    arabic: 'الزيوت',   ml: 'എണ്ണ' },
  { id: 'wood',   label: 'Woods',   arabic: 'الأخشاب',  ml: 'മരം' },
  { id: 'other',  label: 'Other',   arabic: 'أخرى',     ml: 'മറ്റുള്ളവ' },
];

export const PLANTS_DATA = [
  {
    id: 1,
    category: 'resin',
    ArabicName: 'العقاقيه',
    EnglishName: 'Acacia',
    MalayalamName: 'അക്കേഷ്യ',
    ScientificName: 'Acacia Senegal',
    DescriptionEnglish: 'A gum resin used medicinally to soothe irritated areas of the digestive tract. Boiled down and evaporated into an astringent medicine to stop excessive mucous discharge and hemorrhages. Later discovered to serve as a binder for medicinal pellets.',
    DescriptionMalayalam: 'ദഹനേന്ദ്രിയ ഭാഗങ്ങളിലെ ജ്വലനം ശമിപ്പിക്കാൻ ഉപയോഗിക്കുന്ന ഗം റെസിൻ. അമിതമായ ശ്ലേഷ്മ സ്രാവവും രക്തസ്രാവവും നിർത്തുന്ന ഔഷധം ഉണ്ടാക്കാൻ ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Soothing digestive tract irritations; astringent for mucous discharge and hemorrhages; binder for medicinal pellets.',
    UsesMalayalam: 'ദഹനവ്യവസ്ഥ ശമനം; ശ്ലേഷ്മ, രക്തസ്രാവ നിയന്ത്രണം; ഔഷധ ഗുളിക ബൈൻഡർ.',
    PageReference: '23r-2',
    SourcePage: 193,
  },
  {
    id: 2,
    category: 'other',
    ArabicName: 'الحموضة',
    EnglishName: 'Acidic',
    MalayalamName: 'അമ്ലം',
    ScientificName: '',
    DescriptionEnglish: 'Refers to acidic substances added to medicines. Used to moisten the mouth and palate, to reduce acidity in the yellow bile and to prevent harm to the intestinal tract, whose nature was considered to be cold, dry and sinewy.',
    DescriptionMalayalam: 'മരുന്നുകളിൽ ചേർക്കുന്ന അമ്ല പദാർഥങ്ങൾ. വായും അണ്ണാക്കും നനയ്ക്കാനും മഞ്ഞ പിത്തത്തിലെ അമ്ലത കുറയ്ക്കാനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Moisten the mouth and palate; reduce acidity in yellow bile; prevent harm to the intestinal tract.',
    UsesMalayalam: 'വായ്, അണ്ണാക്ക് നനവ്; മഞ്ഞ പിത്ത അമ്ലത കുറക്കൽ; കുടൽ സംരക്ഷണം.',
    PageReference: '25r-16',
    SourcePage: 193,
  },
  {
    id: 3,
    category: 'wood',
    ArabicName: 'عود',
    EnglishName: 'Agar Wood',
    MalayalamName: 'അഗർവുഡ്',
    ScientificName: 'Aquilera malaccensis',
    DescriptionEnglish: 'An aromatic wood known as aloe wood or agar wood. Appears on pages 7r and 4r-15. Used in fumigations.',
    DescriptionMalayalam: 'ആലൂ മരം അല്ലെങ്കിൽ അഗർ മരം എന്നറിയപ്പെടുന്ന സുഗന്ധ മരം. ധൂപ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Used in fumigations.',
    UsesMalayalam: 'ധൂപ ആവശ്യങ്ങൾക്ക് ഉപയോഗിക്കുന്നു.',
    PageReference: '7r, 4r-15',
    SourcePage: 193,
  },
  {
    id: 4,
    category: 'herb',
    ArabicName: 'الفصفصا',
    EnglishName: 'Alfalfa',
    MalayalamName: 'അൽഫൽഫ',
    ScientificName: 'Medicago Satina',
    DescriptionEnglish: 'Appears on page 11v-13. Used in a tea to calm nerve endings, relieving the pain of arthritis and neuralgia. Also used to treat diseases of malnutrition or weight loss.',
    DescriptionMalayalam: 'നാഡി അഗ്രങ്ങൾ ശാന്തമാക്കാൻ ചായ രൂപത്തിൽ ഉപയോഗിക്കുന്നു. സന്ധിവാതം, നാഡീ വേദന ഒഴിവാക്കാൻ ഫലപ്രദം.',
    UsesEnglish: 'Tea to calm nerve endings; relieve arthritis and neuralgia pain; treat malnutrition and weight loss.',
    UsesMalayalam: 'നാഡി ശമനം; സന്ധിവാത, നാഡീ വേദന ആശ്വാസം; പോഷകക്കുറവ്, ഭാരക്കുറവ് ചികിത്സ.',
    PageReference: '11v-13',
    SourcePage: 193,
  },
  {
    id: 5,
    category: 'herb',
    ArabicName: 'صبر',
    EnglishName: 'Aloe Vera',
    MalayalamName: 'കറ്റാർവാഴ',
    ScientificName: 'Aloaceae',
    DescriptionEnglish: 'Appears on pages 15r-20 and 27r-13. An Arabic reference for the juices of all bitter plants, especially aloe vera juice. These juices were used in medicine as purges and tonics, as well as for wound healing.',
    DescriptionMalayalam: 'കൊടും കയ്പ്പേറിയ സസ്യ നീരുകൾ, പ്രത്യേകിച്ചും കറ്റാർ നീര്. ശുദ്ധീകരണ ഔഷധം, ടോണിക്ക്, മുറിവ് ഉണക്കൽ എന്നിവയ്ക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Purges and tonics; wound healing.',
    UsesMalayalam: 'ശുദ്ധീകരണ ഔഷധം; ടോണിക്ക്; മുറിവ് ഉണക്കൽ.',
    PageReference: '15r-20, 27r-13',
    SourcePage: 193,
  },
  {
    id: 6,
    category: 'seed',
    ArabicName: 'لوز',
    EnglishName: 'Almond',
    MalayalamName: 'ബദാം',
    ScientificName: 'Prunus dulcis',
    DescriptionEnglish: 'Appears on page 24r-4. Native to West and Central Asia, common in Palestine and Syria. One of the earliest recognized benefits was preventing intoxication. Used for kidney and bladder disorders, heartburn relief, skin cleansing, and as a component in medicinal ointments.',
    DescriptionMalayalam: 'പശ്ചിമ, മധ്യ ഏഷ്യ സ്വദേശി. ലഹരി തടയൽ, വൃക്ക, മൂത്രാശയ പ്രശ്നങ്ങൾ, നെഞ്ചെരിച്ചിൽ ശമനം, ചർമ്മ ശുദ്ധീകരണം എന്നിവയ്ക്ക് ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Prevent intoxication; kidney and bladder disorders; heartburn relief; skin cleansing; medicinal ointment component; nutritional regimen with sesame, honey, and sugar.',
    UsesMalayalam: 'ലഹരി നിവാരണം; വൃക്ക, മൂത്രാശയ ചികിത്സ; നെഞ്ചെരിച്ചിൽ ശമനം; ചർമ്മ ശുദ്ധീകരണം; ഔഷധ മേൽ‌പ്പൂശൽ.',
    PageReference: '24r-4',
    SourcePage: 194,
  },
  {
    id: 7,
    category: 'flower',
    ArabicName: 'شقايق النعمان',
    EnglishName: 'Anemone',
    MalayalamName: 'അനിമോൺ',
    ScientificName: 'Anemone nemorosa',
    DescriptionEnglish: 'Appears on page 13v, lines 13 and 14. Applied externally for headaches, tertian agues and rheumatic gout. A decoction was highly recommended for the cure of leprosy.',
    DescriptionMalayalam: 'ബാഹ്യ പ്രയോഗം: തലവേദന, ത്രിദിന ജ്വരം, സന്ധിവാതം. കഷായം: കുഷ്ഠരോഗ ചികിത്സ.',
    UsesEnglish: 'Headaches; tertian agues; rheumatic gout (external); decoction for leprosy.',
    UsesMalayalam: 'തലവേദന; ത്രിദിന ജ്വരം; സന്ധിവാതം (ബാഹ്യ); കുഷ്ഠരോഗ കഷായം.',
    PageReference: '13v',
    SourcePage: 194,
  },
  {
    id: 8,
    category: 'herb',
    ArabicName: 'درونج',
    EnglishName: 'Arnica',
    MalayalamName: 'അർണിക്ക',
    ScientificName: 'Arnica montana',
    DescriptionEnglish: 'Appears on pages 10v-1 and 23r-1. Used for pain relief and against bruising.',
    DescriptionMalayalam: 'വേദന ശമനത്തിനും ചതവ് ഭേദമാക്കുന്നതിനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Pain relief; against bruising.',
    UsesMalayalam: 'വേദന ശമനം; ചതവ് ഭേദം.',
    PageReference: '10v-1, 23r-1',
    SourcePage: 194,
  },
  {
    id: 9,
    category: 'resin',
    ArabicName: 'حلتيت / عروق الانجرن',
    EnglishName: 'Asafetida',
    MalayalamName: 'കായം',
    ScientificName: 'Ferula asafoetida',
    DescriptionEnglish: 'Appears on pages 5v, 18r, 21r, and 6v. Has certain medicinal uses; most commonly used as a digestive aid. Reputed to lessen flatulence. Helpful in asthma and bronchitis, and employed against hysteria and nervous afflictions.',
    DescriptionMalayalam: 'ദഹന സഹായി ആയി ഏറ്റവും കൂടുതൽ ഉപയോഗിക്കുന്ന ഔഷധം. വായുക്കുഴപ്പം കുറയ്ക്കുന്നു. ആസ്ത്മ, ബ്രോങ്കൈറ്റിസ്, ഹിസ്റ്റീരിയ, നാഡീ ദൗർബല്യം എന്നിവയ്ക്ക് ഉപകാരപ്രദം.',
    UsesEnglish: 'Digestive aid; reduce flatulence; asthma and bronchitis; hysteria and nervous afflictions.',
    UsesMalayalam: 'ദഹന സഹായം; വായുക്കുഴപ്പം കുറക്കൽ; ആസ്ത്മ, ബ്രോങ്കൈറ്റിസ്; ഹിസ്റ്റീരിയ, നാഡി ദൗർബല്യം.',
    PageReference: '5v, 18r, 21r, 6v',
    SourcePage: 194,
  },
  {
    id: 10,
    category: 'herb',
    ArabicName: 'الغار',
    EnglishName: 'Bay Leaves',
    MalayalamName: 'ബേ ഇല',
    ScientificName: 'Lauris nobilis',
    DescriptionEnglish: 'Found on page 10r-7. Used mainly to treat upper digestive tract disorders and to ease arthritic aches and pains.',
    DescriptionMalayalam: 'ഉപരി ദഹനേന്ദ്രിയ ക്രമക്കേടുകൾ ചികിത്സിക്കാനും സന്ധിവേദന ഒഴിവാക്കാനും ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Upper digestive tract disorders; ease arthritic aches and pains.',
    UsesMalayalam: 'ദഹന ക്രമക്കേട് ചികിത്സ; സന്ധിവേദന ശമനം.',
    PageReference: '10r-7',
    SourcePage: 194,
  },
  {
    id: 11,
    category: 'fruit',
    ArabicName: 'الكاد',
    EnglishName: 'Betal Palm Nut',
    MalayalamName: 'അടക്ക',
    ScientificName: 'Areca catechu',
    DescriptionEnglish: 'Found on page 25r-15. Used medicinally to remove tapeworms and other digestive parasites.',
    DescriptionMalayalam: 'ടേപ്പ്‌വേം, മറ്റ് ദഹന പരാദ ജീവികൾ നീക്കം ചെയ്യാൻ ഔഷധമായി ഉപയോഗിക്കുന്നു.',
    UsesEnglish: 'Remove tapeworms and other digestive parasites.',
    UsesMalayalam: 'ടേപ്പ്‌വേം, ദഹന പരാദ നിർമ്മാർജ്ജനം.',
    PageReference: '25r-15',
    SourcePage: 194,
  },
  {
    id: 12,
    category: 'other',
    ArabicName: 'مرارة',
    EnglishName: 'Bile',
    MalayalamName: 'പിത്തരസം',
    ScientificName: '',
    DescriptionEnglish: 'Various animal biles (snake, crow, wolf, cow, ram, viper, goat, crane) appear throughout the manuscript. Bile was an important part of ancient medicine in both Greece and Rome, considered one of the four humors. Used medicinally for thousands of years across many traditions including Chinese and Islamic medicine.',
    DescriptionMalayalam: 'പല മൃഗങ്ങളുടെ (സർപ്പം, കാക്ക, ചെന്നായ, പശു, ആട്, ക്രൗഞ്ചം) പിത്തരസം ഗ്രന്ഥത്തിൽ കാണുന്നു. ഗ്രീക്ക്, റോം ചികിത്സയിൽ നാലു ദ്രവ്യങ്ങളിൽ ഒന്ന്.',
    UsesEnglish: 'Cut thirst; bind the bowels; treat rheumatic pain, high fever, convulsions, hemorrhoids, bleeding gums, whooping cough, skin infections.',
    UsesMalayalam: 'ദാഹ ശമനം; കുടൽ ബന്ധനം; സന്ധിവേദന, പനി, ബേധം, മൂലം, ചർമ്മ അണുബാധ ചികിത്സ.',
    PageReference: '3r-20, 4r-12, 5v-5, 6r-10, 11r-14, 16v-6',
    SourcePage: 195,
  },
  {
    id: 13,
    category: 'seed',
    ArabicName: 'شونيز',
    EnglishName: 'Black Cumin / Black Onion Seeds',
    MalayalamName: 'കരിഞ്ജീരകം',
    ScientificName: 'Nigella sativa',
    DescriptionEnglish: 'Appears on pages 8v-4 and 19v-14. Black cumin or black onion seed. Traditionally used to stimulate the body\'s energy, aid recovery from fatigue and dispiritedness. Used for respiratory health, stomach and intestinal health, kidney and liver function, circulatory and immune system support, and general overall well-being.',
    DescriptionMalayalam: 'ഊർജ്ജ ഉത്തേജനം, ക്ഷീണ ദൂരീകരണം, ശ്വസന ആരോഗ്യം, ദഹനശക്തി, വൃക്ക, കരൾ പ്രവർത്തനം, രക്ത, പ്രതിരോധ ശക്തി വർദ്ധനവ്.',
    UsesEnglish: 'Stimulate energy; recovery from fatigue; respiratory health; stomach and intestinal health; kidney and liver function; circulatory and immune support; general well-being.',
    UsesMalayalam: 'ഊർജ്ജ ഉത്തേജനം; ക്ഷീണ ദൂരീകരണം; ശ്വസനാരോഗ്യം; ദഹനശക്തി; വൃക്ക, കരൾ ആരോഗ്യം; രക്ത, പ്രതിരോധ ശക്തി.',
    PageReference: '8v-4, 19v-14',
    SourcePage: '195-196',
  },
];