// ═══════════════════════════════════════════════════════════════
// PLANTS & INGREDIENTS DICTIONARY — STANDALONE DATA
// Completely isolated from all calculation engines.
// No imports from any engine or lib file.
// ═══════════════════════════════════════════════════════════════

export const PLANT_CATEGORIES = [
  { id: 'all',       label: 'All',        arabic: 'الكل',          ml: 'എല്ലാം' },
  { id: 'herb',      label: 'Herbs',      arabic: 'الأعشاب',       ml: 'ഔഷധസസ്യങ്ങൾ' },
  { id: 'spice',     label: 'Spices',     arabic: 'التوابل',       ml: 'സുഗന്ധവ്യഞ്ജനങ്ങൾ' },
  { id: 'resin',     label: 'Resins',     arabic: 'الصمغ',         ml: 'റെസിൻ' },
  { id: 'root',      label: 'Roots',      arabic: 'الجذور',        ml: 'വേരുകൾ' },
  { id: 'flower',    label: 'Flowers',    arabic: 'الأزهار',       ml: 'പൂക്കൾ' },
  { id: 'fruit',     label: 'Fruits',     arabic: 'الفواكه',       ml: 'ഫലങ്ങൾ' },
  { id: 'seed',      label: 'Seeds',      arabic: 'البذور',        ml: 'വിത്തുകൾ' },
  { id: 'oil',       label: 'Oils',       arabic: 'الزيوت',        ml: 'എണ്ണകൾ' },
  { id: 'wood',      label: 'Woods',      arabic: 'الأخشاب',       ml: 'മരങ്ങൾ' },
];

export const PLANTS_DATA = [
  {
    id: 1,
    arabic: 'الكمون',
    english: 'Black Cumin',
    malayalam: 'കരിഞ്ജീരകം',
    scientific: 'Nigella sativa',
    category: 'seed',
    uses: 'Used in spiritual fumigation, ruqyah, and as a blessed remedy in Islamic medicine.',
    benefits: 'Strengthens immunity, aids digestion, anti-inflammatory, antioxidant properties. Mentioned in hadith as a cure for every disease except death.',
    warnings: 'Avoid in high doses during pregnancy. May interact with blood-thinning medications.',
  },
  {
    id: 2,
    arabic: 'العود',
    english: 'Agarwood (Oud)',
    malayalam: 'ഊദ്',
    scientific: 'Aquilaria malaccensis',
    category: 'wood',
    uses: 'Burned as incense in spiritual and ritual contexts. Used in Arabic perfumery and purification of spaces.',
    benefits: 'Calming effect, reduces anxiety, promotes spiritual focus. Antibacterial smoke properties.',
    warnings: 'Endangered species — ensure ethical sourcing. Expensive; beware of synthetic substitutes.',
  },
  {
    id: 3,
    arabic: 'الورد',
    english: 'Rose',
    malayalam: 'റോസ്',
    scientific: 'Rosa damascena',
    category: 'flower',
    uses: 'Rose water used in spiritual cleansing, perfume, and food. Rose oil used in aromatherapy.',
    benefits: 'Anti-inflammatory, mood-lifting, skin-soothing. Associated with love and spiritual purity.',
    warnings: 'Allergic reactions possible. Rose oil must be diluted before skin application.',
  },
  {
    id: 4,
    arabic: 'الزعفران',
    english: 'Saffron',
    malayalam: 'കുങ്കുമം',
    scientific: 'Crocus sativus',
    category: 'spice',
    uses: 'Used in writing of amulets (hirz), spiritual ink, food, and as a talisman ingredient.',
    benefits: 'Antidepressant, improves mood and memory, anti-inflammatory, supports heart health.',
    warnings: 'Toxic in large doses (>5g). Avoid during pregnancy in large amounts. Expensive; often adulterated.',
  },
  {
    id: 5,
    arabic: 'اللبان',
    english: 'Frankincense',
    malayalam: 'കുന്തിരിക്കം',
    scientific: 'Boswellia sacra',
    category: 'resin',
    uses: 'Burned for spiritual purification, ward off evil, and in traditional Islamic medicine. Common in ruqyah.',
    benefits: 'Anti-inflammatory, supports joint health, reduces anxiety, antibacterial when burned.',
    warnings: 'May cause skin rash if applied directly. Avoid excessive inhalation of smoke.',
  },
  {
    id: 6,
    arabic: 'المر',
    english: 'Myrrh',
    malayalam: 'മൂർ',
    scientific: 'Commiphora myrrha',
    category: 'resin',
    uses: 'Used in incense blends, traditional medicine, spiritual fumigation, and perfumery.',
    benefits: 'Antiseptic, anti-inflammatory, supports oral health, wound healing. Historically used in embalming.',
    warnings: 'Avoid during pregnancy. May interact with blood sugar medications.',
  },
  {
    id: 7,
    arabic: 'الزنجبيل',
    english: 'Ginger',
    malayalam: 'ഇഞ്ചി',
    scientific: 'Zingiber officinale',
    category: 'root',
    uses: 'Mentioned in the Quran (Surah Al-Insan). Used in herbal medicine and cooking.',
    benefits: 'Aids digestion, anti-nausea, anti-inflammatory, supports circulation and immune system.',
    warnings: 'May cause heartburn in excess. Caution with blood thinners. Avoid in large doses when pregnant.',
  },
  {
    id: 8,
    arabic: 'الحبة السوداء',
    english: 'Black Seed',
    malayalam: 'കരിംജീരകം',
    scientific: 'Nigella sativa',
    category: 'seed',
    uses: 'Prophetic medicine. Used in ruqyah, cooking, and as a general health supplement.',
    benefits: 'Immune booster, antimicrobial, helps with asthma, blood pressure, and diabetes management.',
    warnings: 'Large doses may cause kidney or liver issues. Not for long-term use without breaks.',
  },
  {
    id: 9,
    arabic: 'القرنفل',
    english: 'Clove',
    malayalam: 'ഗ്രാമ്പൂ',
    scientific: 'Syzygium aromaticum',
    category: 'spice',
    uses: 'Used in incense, spiritual fumigation, oral care, and cooking.',
    benefits: 'Powerful antiseptic, numbs pain (especially toothache), antifungal, rich in antioxidants.',
    warnings: 'Clove oil is potent — must be diluted. Avoid in children. May slow blood clotting.',
  },
  {
    id: 10,
    arabic: 'الكافور',
    english: 'Camphor',
    malayalam: 'കർപ്പൂരം',
    scientific: 'Cinnamomum camphora',
    category: 'resin',
    uses: 'Mentioned in Quran (Surah Al-Insan). Used in purification rituals, ghusl of the deceased, and incense.',
    benefits: 'Cooling, decongestant, insect repellent, mild analgesic.',
    warnings: 'Toxic if ingested in large amounts. Keep away from children and open flames.',
  },
  {
    id: 11,
    arabic: 'الصندل',
    english: 'Sandalwood',
    malayalam: 'ചന്ദനം',
    scientific: 'Santalum album',
    category: 'wood',
    uses: 'Burned as incense, used in spiritual perfumes, paste applied in rituals.',
    benefits: 'Calming, reduces anxiety and stress, antiseptic, skin-soothing.',
    warnings: 'Endangered; ensure ethical sourcing. Avoid synthetic sandalwood oils for ritual use.',
  },
  {
    id: 12,
    arabic: 'الهيل',
    english: 'Cardamom',
    malayalam: 'ഏലം',
    scientific: 'Elettaria cardamomum',
    category: 'spice',
    uses: 'Used in Arabic qahwa (coffee), cooking, and as a digestive remedy.',
    benefits: 'Improves digestion, freshens breath, diuretic, antioxidant, may lower blood pressure.',
    warnings: 'Generally safe. Excessive use may cause gallstone issues in susceptible individuals.',
  },
  {
    id: 13,
    arabic: 'السنا',
    english: 'Senna',
    malayalam: 'സെന്ന',
    scientific: 'Cassia senna',
    category: 'herb',
    uses: 'Mentioned in Islamic medicine (Tibb al-Nabawi). Used as a laxative herbal remedy.',
    benefits: 'Effective laxative, used for constipation relief, liver cleansing.',
    warnings: 'Not for long-term use. Avoid during pregnancy. May cause electrolyte imbalance.',
  },
  {
    id: 14,
    arabic: 'الحلبة',
    english: 'Fenugreek',
    malayalam: 'ഉലുവ',
    scientific: 'Trigonella foenum-graecum',
    category: 'seed',
    uses: 'Used in traditional Islamic medicine, cooking, and as a galactagogue (increases milk production).',
    benefits: 'Regulates blood sugar, improves digestion, anti-inflammatory, supports lactation.',
    warnings: 'Avoid in pregnancy (uterine stimulant). May lower blood sugar — caution with diabetes medication.',
  },
  {
    id: 15,
    arabic: 'الزيتون',
    english: 'Olive',
    malayalam: 'ഒലിവ്',
    scientific: 'Olea europaea',
    category: 'fruit',
    uses: 'Mentioned multiple times in the Quran. Olive oil used medicinally, in cooking, and skin care.',
    benefits: 'Heart-healthy fats, anti-inflammatory, antioxidant-rich, skin-nourishing.',
    warnings: 'High in calories. Rancid olive oil loses benefits. Use cold-pressed extra virgin only.',
  },
  {
    id: 16,
    arabic: 'العسل',
    english: 'Honey',
    malayalam: 'തേൻ',
    scientific: 'Apis mellifera (product)',
    category: 'herb',
    uses: 'Mentioned in Quran (Surah An-Nahl) as a healing. Used in ruqyah remedies and medicine.',
    benefits: 'Antibacterial, wound-healing, soothes throat, rich in antioxidants, energy-giving.',
    warnings: 'Not for infants under 1 year (botulism risk). High sugar content for diabetics.',
  },
  {
    id: 17,
    arabic: 'البخور',
    english: 'Incense (Benzoin)',
    malayalam: 'ലോബൻ',
    scientific: 'Styrax benzoin',
    category: 'resin',
    uses: 'Used in spiritual fumigation, warding off evil eye, and purifying spaces.',
    benefits: 'Antiseptic smoke, calming aroma, traditionally believed to repel negative energies.',
    warnings: 'Avoid continuous inhalation. Ensure good ventilation when burning.',
  },
  {
    id: 18,
    arabic: 'الكمون الرومي',
    english: 'Cumin',
    malayalam: 'ജീരകം',
    scientific: 'Cuminum cyminum',
    category: 'seed',
    uses: 'Used in cooking and as a medicinal herb in Islamic tradition.',
    benefits: 'Aids digestion, iron-rich, anti-bloating, antioxidant, may aid weight management.',
    warnings: 'Generally safe. May slow blood clotting in large amounts.',
  },
  {
    id: 19,
    arabic: 'المصطكى',
    english: 'Mastic',
    malayalam: 'മസ്തകി',
    scientific: 'Pistacia lentiscus',
    category: 'resin',
    uses: 'Used in traditional Islamic medicine, spiritual remedies, and as a chewing gum resin.',
    benefits: 'Heals stomach ulcers, antibacterial, supports oral health and liver function.',
    warnings: 'Generally safe. Rare allergic reactions reported.',
  },
  {
    id: 20,
    arabic: 'الحناء',
    english: 'Henna',
    malayalam: 'മൈലാഞ്ചി',
    scientific: 'Lawsonia inermis',
    category: 'herb',
    uses: 'Sunnah practice for hair and body. Used in Islamic weddings and as a skin conditioner.',
    benefits: 'Natural hair dye, cooling on skin, antibacterial, antifungal.',
    warnings: '"Black henna" (with PPD) is dangerous — causes severe allergic reactions. Use only natural henna.',
  },
];