// ═══════════════════════════════════════════════════════════════
//  MULTILINGUAL LABELS — English / Arabic / Malayalam
// ═══════════════════════════════════════════════════════════════
const L = {
  en: {
    title:         "Magic Square — Sacred Vefk",
    subtitle:      "Traditional Construction System",
    baseNumber:    "🔢 Base Number",
    gridSize:      "Grid Size",
    element:       "Element",
    generate:      "Generate Magic Square",
    suffix:        "Suffix System",
    suffixNone:    "No Suffix",
    suffixArabic:  "Arabic Suffix (−41)",
    suffixHebrew:  "Hebrew Suffix (−31)",
    inputLabel:    "Input Number",
    workingMC:     "Magic Constant (MC)",
    usurper:       "Usurper (Min Cell)",
    guide:         "Guide (Max Cell)",
    mystery:       "Mystery",
    adjuster:      "Adjuster (Magic Constant)",
    leader:        "Leader",
    regulator:     "Regulator",
    genGov:        "General Governor",
    highOver:      "High Overseer",
    angelAr:       "Angel (Arabic)",
    angelHeb:      "Angel (Hebrew)",
    jinnAr:        "Jinn (Arabic)",
    jinnHeb:       "Jinn (Hebrew)",
    hierarchy:     "📜 Hierarchy Table",
    compatible:    "Compatible Sizes",
    incompatible:  "⚠️ Incompatible with this grid size",
    compatSizes:   "Compatible Grid Sizes",
    planet:        "🪐 Associated Planet",
    negFix:        "+360 applied (negative fix)",
    subtracted:    "Suffix subtracted",
    verification:  "⚖ Verification Report",
    mcLabel:       "Magic Constant",
    rows:          "Rows",
    columns:       "Columns",
    diag1:         "Diagonal ↘",
    diag2:         "Diagonal ↙",
    trueSquare:    "✦ True Magic Square",
    letterTable:   "📖 Letter Value Tables",
    arabicTable:   "Arabic Abjad",
    hebrewTable:   "Hebrew Gematria",
    nameConstruct: "Spiritual Name Construction",
    inputValue:    "Input Value",
    letterResult:  "Letter Result",
    planetReport:  "🪐 Planet Report",
    totalCells:    "Total Cells",
    totalValue:    "Total Square Value (Leader)",
    fire: "Fire", air: "Air", earth: "Earth", water: "Water",
    saturn:"Saturn", jupiter:"Jupiter", mars:"Mars", sun:"Sun",
    venus:"Venus", mercury:"Mercury", moon:"Moon",
  },
  ar: {
    title:         "المربع السحري — وفق مقدس",
    subtitle:      "نظام البناء التقليدي",
    baseNumber:    "🔢 الرقم الأساسي",
    gridSize:      "حجم المربع",
    element:       "العنصر",
    generate:      "توليد المربع السحري",
    suffix:        "نظام اللاحقة",
    suffixNone:    "بدون لاحقة",
    suffixArabic:  "لاحقة عربية (−٤١)",
    suffixHebrew:  "لاحقة عبرية (−٣١)",
    inputLabel:    "الرقم المُدخل",
    workingMC:     "الثابت السحري (MC)",
    usurper:       "المغتصب (أصغر خانة)",
    guide:         "الدليل (أكبر خانة)",
    mystery:       "الغموض",
    adjuster:      "المُعدِّل (الثابت السحري)",
    leader:        "القائد",
    regulator:     "المنظِّم",
    genGov:        "الحاكم العام",
    highOver:      "المراقب الأعلى",
    angelAr:       "قيمة الملاك (عربي)",
    angelHeb:      "قيمة الملاك (عبري)",
    jinnAr:        "قيمة الجن (عربي)",
    jinnHeb:       "قيمة الجن (عبري)",
    hierarchy:     "📜 جدول التسلسل الهرمي",
    compatible:    "أحجام متوافقة",
    incompatible:  "⚠️ الرقم غير متوافق مع هذا الحجم",
    compatSizes:   "الأحجام المتوافقة",
    planet:        "🪐 الكوكب المرتبط",
    negFix:        "تم إضافة ٣٦٠ لتصحيح القيمة السالبة",
    subtracted:    "تم طرح اللاحقة",
    verification:  "⚖ تقرير التحقق",
    mcLabel:       "الثابت السحري",
    rows:          "الصفوف",
    columns:       "الأعمدة",
    diag1:         "القطر ↘",
    diag2:         "القطر ↙",
    trueSquare:    "✦ مربع سحري حقيقي",
    letterTable:   "📖 جدول قيم الحروف",
    arabicTable:   "الأبجد العربي",
    hebrewTable:   "الجماتريا العبرية",
    nameConstruct: "نظام استخراج الأسماء الروحية",
    inputValue:    "القيمة المُدخلة",
    letterResult:  "نتيجة الحروف",
    planetReport:  "🪐 تقرير الكوكب",
    totalCells:    "إجمالي الخلايا",
    totalValue:    "القيمة الكلية للمربع (القائد)",
    fire:"النار", air:"الهواء", earth:"التراب", water:"الماء",
    saturn:"الزحل", jupiter:"المشتري", mars:"المريخ", sun:"الشمس",
    venus:"الزهرة", mercury:"العطارد", moon:"القمر",
  },
  ml: {
    title:         "മാജിക്ക് സ്ക്വയർ — പവിത്ര വെഫ്ക്",
    subtitle:      "പരമ്പരാഗത നിർമ്മാണ സംവിധാനം",
    baseNumber:    "🔢 അടിസ്ഥാന സംഖ്യ",
    gridSize:      "ഗ്രിഡ് വലുപ്പം",
    element:       "തത്ത്വം (ഭൂതം)",
    generate:      "മാജിക്ക് സ്ക്വയർ ഉണ്ടാക്കുക",
    suffix:        "പ്രത്യയ സംവിധാനം",
    suffixNone:    "പ്രത്യയം ഇല്ല",
    suffixArabic:  "അറബി പ്രത്യയം (−41)",
    suffixHebrew:  "ഹീബ്രു പ്രത്യയം (−31)",
    inputLabel:    "നൽകിയ സംഖ്യ",
    workingMC:     "മാജിക്ക് കോൺസ്ടന്റ് (MC)",
    usurper:       "ഉർജർ (ഏറ്റവും ചെറിയ സെൽ)",
    guide:         "ഗൈഡ് (ഏറ്റവും വലിയ സെൽ)",
    mystery:       "മിസ്ററി",
    adjuster:      "അഡ്ജസ്ടർ (മാജിക്ക് കോൺസ്ടന്റ്)",
    leader:        "ലീഡർ",
    regulator:     "റെഗുലേറ്റർ",
    genGov:        "ജനറൽ ഗവർണർ",
    highOver:      "ഹൈ ഓവർസിയർ",
    angelAr:       "മലക്ക് (അറബി)",
    angelHeb:      "മലക്ക് (ഹീബ്രു)",
    jinnAr:        "ജിന്ന് (അറബി)",
    jinnHeb:       "ജിന്ന് (ഹീബ്രു)",
    hierarchy:     "📜 ശ്രേണി പട്ടിക",
    compatible:    "അനുയോജ്യ വലുപ്പങ്ങൾ",
    incompatible:  "⚠️ ഈ ഗ്രിഡ് വലുപ്പത്തിന് അനുയോജ്യമല്ല",
    compatSizes:   "അനുയോജ്യ ഗ്രിഡ് വലുപ്പങ്ങൾ",
    planet:        "🪐 ഗ്രഹ ബന്ധം",
    negFix:        "ഋണ മൂല്യം: 360 കൂട്ടി",
    subtracted:    "പ്രത്യയം കുറച്ചു",
    verification:  "⚖ സ്ഥിരീകരണ റിപ്പോർട്ട്",
    mcLabel:       "മാജിക്ക് കോൺസ്ടന്റ്",
    rows:          "വരികൾ",
    columns:       "നിരകൾ",
    diag1:         "വിഭജനം ↘",
    diag2:         "വിഭജനം ↙",
    trueSquare:    "✦ യഥാർഥ മാജിക്ക് സ്ക്വയർ",
    letterTable:   "📖 അക്ഷര മൂല്യ പട്ടിക",
    arabicTable:   "അറബി അബ്ജദ്",
    hebrewTable:   "ഹീബ്രു ഗെമാത്രിയ",
    nameConstruct: "ആത്മീയ നാമ നിർമ്മാണം",
    inputValue:    "നൽകിയ മൂല്യം",
    letterResult:  "അക്ഷര ഫലം",
    planetReport:  "🪐 ഗ്രഹ റിപ്പോർട്ട്",
    totalCells:    "ആകെ സെല്ലുകൾ",
    totalValue:    "ആകെ മൂല്യം (ലീഡർ)",
    fire:"അഗ്നി", air:"വായു", earth:"ഭൂമി", water:"ജലം",
    saturn:"ശനി", jupiter:"വ്യാഴം", mars:"ചൊവ്വ", sun:"സൂര്യൻ",
    venus:"ശുക്രൻ", mercury:"ബുധൻ", moon:"ചന്ദ്രൻ",
  },
};

export default L;